---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: mediabox
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      main:
        type: statefulset
        containers:
          bazarr:
            image:
              repository: ghcr.io/onedr0p/bazarr
              tag: 1.5.1
            env:
              TZ: "Etc/UTC"
              BAZARR__INSTANCE_NAME: Bazarr
              BAZARR__PORT: &port 6767
              BAZARR__LOG_LEVEL: info
              BAZARR__ANALYTICS_ENABLED: "False"
              BAZARR__POSTGRES_HOST:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-bazarr-app
                    key: host
              BAZARR__POSTGRES_MAIN_DB: bazarr_main
              BAZARR__POSTGRES_LOG_DB: bazarr_log
              BAZARR__POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-bazarr-app
                    key: user
              BAZARR__POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-bazarr-app
                    key: password
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      dnsConfig:
        nameservers:
          - 1.1.1.1
        options:
          - { name: ndots, value: "1" }
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: *port
            protocol: HTTP
    persistence:
      config:
        enabled: true
        storageClass: sunbeam-nfs-csi
        accessMode: "ReadWriteOnce"
        size: 1Gi
        advancedMounts:
          main:
            bazarr:
              - path: /config
