---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
  namespace: traefik-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 34.2.0
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 60m
  values:
    ports:
      web:
        port: 80
        transport:
          respondingTimeouts:
            readTimeout: 0s
        redirections:
          to: websecure
          scheme: https
      websecure:
        port: 443
        asDefault: true
        tls:
          enabled: true
        transport:
          respondingTimeouts:
            readTimeout: 0s
        middlewares:
          - traefik-system-secure-headers-middleware
      ldap:
        port: 389
        protocol: TCP
        expose:
          default: false
          ldap: true
        tls:
          enabled: false

    service:
      spec:
        externalTrafficPolicy: Local
      annotations:
        external-dns.alpha.kubernetes.io/enabled: "true"
        external-dns.alpha.kubernetes.io/hostname: "proxy-internal.layertwo.dev"
        kubernetes.io/ingress.class: &ingressName internal
        metallb.io/address-pool: internal
        metallb.io/loadBalancerIPs: "172.31.0.20"
      additionalServices:
        ldap:
          type: LoadBalancer
          externalTrafficPolicy: Local
          annotations:
            external-dns.alpha.kubernetes.io/enabled: "true"
            external-dns.alpha.kubernetes.io/hostname: "ldap.internal.layertwo.dev"
            kubernetes.io/ingress.class: *ingressName
            metallb.io/address-pool: internal
            metallb.io/loadBalancerIPs: "172.31.0.21"

    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 4

    ingressClass:
      enabled: true
      isDefaultClass: true
      name: *ingressName

    ingressRoute:
      dashboard:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: "traefik-internal.layertwo.dev"
          external-dns.alpha.kubernetes.io/target: "proxy-internal.layertwo.dev"
        entryPoints: ["websecure"]
        matchRule: Host(`traefik-internal.layertwo.dev`)

    providers:

      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
        ingressClass: *ingressName

      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        ingressClass: *ingressName
        publishedService:
          enabled: false

    logs:
      access:
        enabled: true
    globalArguments: []
