---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
  namespace: traefik-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 33.2.1
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 60m
  values:
    ports:
      web:
        port: 80
        redirectTo: websecure
        transport:
          respondingTimeouts:
            readTimeout: 0s
        redirectTo:
          port: websecure
      websecure:
        port: 443
        tls:
          enabled: true
        transport:
          respondingTimeouts:
            readTimeout: 0s
      ldap:
        port: 389
        protocol: TCP
        expose: 
          default: false
          ldap: true
        tls:
          enabled: false

    service:
      spec:
        externalTrafficPolicy: Local
      annotations:
        external-dns.alpha.kubernetes.io/enabled: "true"
        external-dns.alpha.kubernetes.io/hostname: "proxy-internal.layertwo.dev"
        kubernetes.io/ingress.class: &ingressName internal
        metallb.io/address-pool: internal
        metallb.io/loadBalancerIPs: "172.31.0.20"
      additionalServices: 
        ldap:
          type: LoadBalancer
          externalTrafficPolicy: Local
          annotations:
            external-dns.alpha.kubernetes.io/enabled: "true"
            external-dns.alpha.kubernetes.io/hostname: "ldap.internal.layertwo.dev"
            kubernetes.io/ingress.class: &ingressName internal
            metallb.io/address-pool: internal
            metallb.io/loadBalancerIPs: "172.31.0.21"

    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 4

    ingressClass:
      enabled: true
      isDefaultClass: true
      name: *ingressName

    ingressRoute:
      dashboard:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: "traefik-internal.layertwo.dev"
          external-dns.alpha.kubernetes.io/target: "proxy-internal.layertwo.dev"
        entryPoints: ["websecure"]
        matchRule: Host(`traefik-internal.layertwo.dev`)

    providers:

      kubernetesCRD:
        allowCrossNamespace: true
        ingressClass: *ingressName

      kubernetesIngress:
        ingressClass: *ingressName

    logs:
      access:
        enabled: true
    globalArguments: []
