---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-pangolin
  namespace: unfabric
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  imageName: ghcr.io/cloudnative-pg/postgresql:16.14
  storage:
    storageClass: sunbeam-nfs-csi
    size: 1Gi
