---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugin-gpu
  namespace: kube-system
spec:
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.32.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  interval: 60m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: intel-device-plugin-operator
  values:
    name: intel-gpu-plugin
    sharedDevNum: 3
    nodeFeatureRule: true
