# sops --encrypt --in-place clusters/home/apps/cloud/nextcloud/valkey/secrets-nextcloud-valkey.sops.yml
apiVersion: v1
kind: Secret
metadata:
  name: secrets-nextcloud-valkey
  namespace: nextcloud
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:s3gs3VH/fWy0Svfjh/xLGQPxEz+p79Wbw9b9UYN36IC4W64vP4QCLPLnZfaxVvRU9I7JB+Ya8tOU1IA3kv+h7g==,iv:r1iCBzAv6zjVyK3PyeE+8aMBEExuwteXq1KZiMcm40Y=,tag:AMc30ZH89JlTD93jLeLBgw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdkFwd1FTbjhwZW90eGNT
        aVA1Y3JvOHQrOGJISXg3TUs3ZGtQNDVBbDJZCjFFMG1uMEVyckFzTGE0MkJCckxS
        K0lhVDE1dnN6VFpBKzBaWnlyV01MM1UKLS0tIFdhQW1EdzlORnY4S2diRHUxNEEv
        dTF3MTl6YzVCS2htYUlvOE52bHQvWnMKd/teS89q6copwfXoMeY5IyjA0BMdJ6LY
        r7a4eYEL+SEBNF9mco6Ej3uYiYsVWxA8oPsmUipiZwDJPW7qWu2iCA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T04:40:15Z"
  mac: ENC[AES256_GCM,data:QOdMzdOFBvM0IqAE/Vcv1XMTKUGsZCGU7gYGHgb8q/CMyxIXfh9ysl0bLj7NXbQVcfy2H6Xlhr6bDBS5Sk+Zla9tSvv7DlVThZ2PdJSk2ucrelb0BzYmgTsarIuRKu8t3TksEM4snfl+/SXpBflZN5FlL6GE24QYjwXHcHoSD2o=,iv:vHtpvgAiYyHnRWNZfZeSVdOrsMfgF5uqzcqULQnoV/E=,tag:UApYwvKgbS5l8uArHS7i8w==,type:str]
  version: 3.13.3
