---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-redis
  namespace: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.4.1-alpine3.20
            command:
              - sh
            args:
              - -c
              - >-
                redis-server --requirepass $REDIS_PASSWORD
            env:
              REDIS_PORT: &port 6379
              REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: secrets-immich-redis
                    key: REDIS_PASSWORD
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 256M
    service:
      main:
        enabled: true
        controller: main
        ports:
          redis:
            enabled: true
            port: *port
