apiVersion: v1
kind: Secret
metadata:
  name: pushover
  namespace: flux-system
type: Opaque
stringData:
  address: ENC[AES256_GCM,data:tNMc8LTplv80iGRiHNqA5WJvhKEXWM57uz+DLCoI9qjp4ZT8WH4uEPp343XylBZoTdu+VFxdsWD7t1iJYhrrGq4e+8IlhS4=,iv:ltcogGwrvcc0oIDL+JjswwqmTTFX18Uss3OOTrpejCg=,tag:hN38uRK9kjZkkvfLToGocw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybGdidlhkTjJZSFJIWVVG
        VHBtR1VMczBxS05nOUlybVhTVjY5WGw3SlNBCmMxOHVLa213aURSRHhFa0pkU04x
        dWZkWGpGM0wzNTAzbjdqeUFqeG1UUFUKLS0tIHlMaFlJQWJ4T21Za3ZrSnExVUxN
        TFc2UURIdng2TkxWY3lUUlpEUnJNdmMKEYwFSX4bECRDX+dfHbdsQV5LHUrF5Sv+
        wurBqYwYmO29A1GJWZuR9t8DhOIPzF5iyda/SAkcneeU35Nb8aVDMQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T05:40:06Z"
  mac: ENC[AES256_GCM,data:AB4Ron65yot+wC4rEyVmO1QUheK9McPHfnGe7BkWsYJG/GeuPSWu66+vyQfTcWs8W24Dbzb/mGlv7NyjPXmdQTvocEPnSkZCfSYKIZvZvQ+amK8nboMV65GrYMcKTiq2acR5HEtQtLgdG1Rfb3x0CZYMy62ORnThs5rqwHL8fTg=,iv:k3ZGKF3LLPgQmPHBnjxAot+4/ZMzAnp0jhugo5RyeFs=,tag:mRzDoTkITrjY98dNxYhZqg==,type:str]
  version: 3.13.2
