---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - release.yml
  - secrets-pushover.sops.yml
  - secrets-truenas.sops.yml
  - ingressroute.yml
  - pdb.yml
  - postgres
