---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: gatus
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: twin
        namespace: flux-system
  values:
    annotations:
      reloader.stakater.com/auto: "true"
    image:
      repository: twinproduction/gatus
      tag: latest

    env:
      PUSHOVER_TOKEN:
        valueFrom:
          secretKeyRef:
            name: gatus-pushover
            key: PUSHOVER_TOKEN
      PUSHOVER_USER_KEY:
        valueFrom:
          secretKeyRef:
            name: gatus-pushover
            key: PUSHOVER_USER_KEY
      POSTGRES_URI:
        valueFrom:
          secretKeyRef:
            name: cnpg-gatus-app
            key: uri
      OIDC_CLIENT_ID:
        valueFrom:
          secretKeyRef:
            name: gatus-oidc
            key: CLIENT_ID
      OIDC_CLIENT_SECRET:
        valueFrom:
          secretKeyRef:
            name: gatus-oidc
            key: CLIENT_SECRET
      TRUENAS_API_KEY:
        valueFrom:
          secretKeyRef:
            name: gatus-truenas
            key: API_KEY

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /config
        hostPathType: Directory
        readOnly: true

    service:
      main:
        ports:
          https:
            port: 8080

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 256Mi
    config:
      storage:
        type: postgres
        path: "${POSTGRES_URI}"

      endpoints:

        - name: hermes-agent
          group: ai
          url: https://hermes.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "hermes-agent is down"

        - name: saml-bridge
          group: infrastructure
          url: https://aws-sso.layertwo.dev/health
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "saml-bridge is down"

        - name: pocket-id
          group: infrastructure
          url: https://idp.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "pocket-id is down"

        - name: send
          group: external
          url: https://send.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 401"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "send is down"

        - name: layertwo.dev
          group: external
          url: https://www.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "layertwo.dev website is down"

        - name: immich
          group: media
          url: https://immich.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "immich is down"

        - name: forgejo
          group: external
          url: https://code.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "forgejo is down"

        - name: jellyfin
          group: media
          url: https://jellyfin.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "jellyfin is down"

        - name: bazarr
          group: media
          url: https://bazarr.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 401"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "bazarr is down"

        - name: prowlarr
          group: media
          url: https://prowlarr.layertwo.dev/ping
          interval: 1m
          conditions:
            - "[STATUS] == 200"
            - "[BODY].status == OK"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "prowlarr is down"

        - name: qbittorrent
          group: media
          url: https://qt.layertwo.dev/api/v2/app/version
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "qbittorent is down"

        - name: radarr
          group: media
          url: https://radarr.layertwo.dev/ping
          interval: 1m
          conditions:
            - "[STATUS] == 200"
            - "[BODY].status == OK"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "radarr is down"

        - name: sonarr
          group: media
          url: https://sonarr.layertwo.dev/ping
          interval: 1m
          conditions:
            - "[STATUS] == 200"
            - "[BODY].status == OK"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "sonarr is down"

        - name: home-assistant
          group: home
          url: https://hass.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "home-assistant is down"

        - name: mqtt-dashboard
          group: home
          url: https://mqtt-dashboard.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "mqtt-dashboard is down"

        - name: mqtt-listeners
          group: home
          url: tcp://mqtt-listeners.home-assistant.svc.cluster.local:1883
          interval: 1m
          conditions:
            - "[CONNECTED] == true"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "mqtt-listeners is down"

        - name: zigbee2mqtt
          group: home
          url: https://zigbee.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "zigbee2mqtt is down"

        - name: zwave
          group: home
          url: https://zwave.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "zwave is down"

        - name: goldilocks
          group: infrastructure
          url: https://goldilocks.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "goldilocks is down"

        - name: truenas
          group: infrastructure
          url: https://sunbeam.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "truenas is down"

        - name: truenas-system
          group: infrastructure
          url: https://sunbeam.layertwo.dev/api/v2.0/system/state
          interval: 5m
          headers:
            Authorization: "Bearer ${TRUENAS_API_KEY}"
          conditions:
            - "[STATUS] == 200"
            - "[BODY] == pat(*READY*)"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 2
              success-threshold: 2
              send-on-resolved: true
              description: "truenas system is not ready"

        - name: truenas-pool
          group: infrastructure
          url: https://sunbeam.layertwo.dev/api/v2.0/pool
          interval: 5m
          headers:
            Authorization: "Bearer ${TRUENAS_API_KEY}"
          conditions:
            - "[STATUS] == 200"
            - "[BODY] == pat(*\"status\": \"ONLINE\"*)"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 2
              success-threshold: 2
              send-on-resolved: true
              description: "truenas pool is unhealthy"

        - name: garage
          group: infrastructure
          url: https://s3.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 403"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "garage is down"

        - name: traefik-external
          group: infrastructure
          url: https://traefik-external.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: false
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "traefik-external is down"

        - name: traefik-internal
          group: infrastructure
          url: https://traefik-internal.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "traefik-internal is down"

        - name: cloudtak
          group: tak
          url: https://cloudtak.layertwo.dev
          interval: 1m
          conditions:
            - "[STATUS] < 500"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "cloudtak is down"

        - name: cloudtak-media
          group: tak
          url: tcp://media.cloudtak.layertwo.dev:8554
          interval: 1m
          conditions:
            - "[CONNECTED] == true"
          alerts:
            - type: pushover
              enabled: true
              failure-threshold: 3
              success-threshold: 2
              send-on-resolved: true
              description: "cloudtak-media is down"

      alerting:
        pushover:
          application-token: "${PUSHOVER_TOKEN}"
          user-key: "${PUSHOVER_USER_KEY}"

      security:
        oidc:
          issuer-url: https://idp.layertwo.dev
          client-id: "${OIDC_CLIENT_ID}"
          client-secret: "${OIDC_CLIENT_SECRET}"
          redirect-url: "https://status.layertwo.dev/authorization-code/callback"
          scopes: [openid]
