apiVersion: v1
kind: Secret
metadata:
  name: gatus-oidc
  namespace: monitoring
type: Opaque
stringData:
  CLIENT_ID: ENC[AES256_GCM,data:1L+qrVia9ZckBEu5nu8iiZE7IUcyffwA53vPCpbJXVlqpkNU,iv:Eb946mYXSsiGzKuM6SpiehpTiKKxj/jMx9wUYp84psc=,tag:DNwCUZ+aJTmj9MpR3Q2s5A==,type:str]
  CLIENT_SECRET: ENC[AES256_GCM,data:cMGI0oNICBNewbCOiJCVx3yOeBVN5NFAY5gNCbtr2EI=,iv:ogL7U28U2Zl87K21TJ0uJ96beCujAxewujjKiRRQsfo=,tag:MIulbKtf1mCtNdLjzHfiWw==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcmN5Q1BmMlJCYnVhZVVs
        WlZzd1dmZUJZNmNuYlZnQ2UwSVJia1lpdmdJCjFId2FncDVYeFhNaEFJVlQ2dEQ4
        b09aNEE5UUtIVGY3WkpUVXB2bDJ2QkEKLS0tIDdtZm5ydlgyb3dEQkoycWZxUE5w
        TjM3bnJiZ2VUNjhjRStJc0FTQm13SEEK/azvw96/7v+5h8MLVlB5lP9BRoss2+Dw
        5pqzb6EbIkmPe5iKymfim+dlIimssrfohqw0MKEzXo+igevS2j8kKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T05:25:45Z"
  mac: ENC[AES256_GCM,data:YL3i53Q/KDnBRIBHE1pFGtw2QggmgyZSowOITSDHBzIteDnqiQYqJ66HELX2M7XbmgcWEcK8QYQp5CNcL9+kD2rWuj1PFYVRhKBL7n/tIULvBRYQ+aw2Rh+sV4yDb3q5n/0QZpsNpv35vTdknc8aAARW6Z4Zrp8W6ppQebsEhKs=,iv:dLLq+xczXhwvHkVDhvJasKKAGDsQwKyhEGm4GR3u+6Q=,tag:37XUu/tTuo+Rco6paKmydw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
