apiVersion: v1
kind: Secret
metadata:
  name: gatus-pushover
  namespace: monitoring
type: Opaque
stringData:
  PUSHOVER_TOKEN: ENC[AES256_GCM,data:qhnQMHS3fp3xfHzXVi347unH0uIJHS7y/u6r1hFb,iv:IPmwhVPLIVxz2oShd8OY3pC92ssRNxavhk5QDTJkeNI=,tag:njW1Hd51zVfVBNxruXFJKQ==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:GxUB/gUTujNcyoD3DHXMwYXUJCwPY4ACT4WJLiE5,iv:iHOFj+An1eKUnahJGJFeENR4B+3iVs2fO9D97ogRat0=,tag:KIPdt8AGwB9XyfKRr3hOsA==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiblRwUkxHcmxxb1QwSGVh
        OCtCaGhpdk9LZGw1OGJ1TWw1ZXBubktkekhzCjRSdlBGcE0xaCtudjFFVkJqTXIx
        bEdvTzZCMzg0WmFRem4zWmNwZVFGVWMKLS0tICtyNTljRzFkWUo2WGFuS0tFZzRj
        Lzl3VWx4b3Fnbk5xTS96c0x6bGVkaWsKp3E2OfiBD3odwrC+unM4CsqcU9fnMwg8
        tNn19VMF+X2xsv3zIhQnnOmSIMqGGA2YlFM6VD4UxDvc+nGn9TvjPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-18T04:43:18Z"
  mac: ENC[AES256_GCM,data:tx68uK7NlBgzCpvonbi18MqHBAyfR77EZl4k23zi/jYvQJqa7irvyqJnSI2wdHfygpfobKz3OgOaM/gE5PzgGMDBBWIDvPQtWw44w3g0NYzs0lCnuANlF5snZ2VwrkbKr4LJy+TOOHoRJUactxHqbTNEjDeYPcW1Yn3/e3F8JGA=,iv:45/QCEX1ZX2k8QdIw/LIklh9FSTAoGHyX2FcLmcaqO8=,tag:wmDFiI/d1YhfuwrY8PpMug==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
