apiVersion: v1
kind: Secret
metadata:
  name: gatus-truenas
  namespace: monitoring
type: Opaque
stringData:
  API_KEY: ENC[AES256_GCM,data:Qn3XZzBYQG9pT493Jp7h3O838g2hS86479S1gz8vcYyXAORUAYyFMgq0anqusytbl3/cFTGfOwmh2dpd6qnjlkUv,iv:Zgci5a/2koZoX+2j3Ui9YffV0ulKjnZAAXeyCatTBno=,tag:LjIJsrpSXC85CuVTemv6uw==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dDdMUldWbVlOY2VmSTl3
        aGlRMVJxSXgrZ0twZG1QTGpOVzRqNGRLSDFNCi9YS2FicjM1bEVtK0VRSnlKbU8r
        SlVZeXQ1ak94Ykxyait6ZjBpbFI3RVEKLS0tIGJGQ2dVODhLTzdBc1hJRjB1WUx0
        OWtmc0J6eHdvS0JUck5CbjNGWE9vOVEKmBaufpcoi8mCKaoT7CSIxR2urmdjhzXz
        +zhtt1WSUQ80MJnsRgsb/WFmB5PwQfNVYM10en5sMqzTXQTI2UPpOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T07:12:48Z"
  mac: ENC[AES256_GCM,data:dj1oG459QPKAvgXHNvHjRSPTM5j5snjVs3GaGi8n+YF07VUD//8DpaGzb3Ntb6SxlExL5YT9cWQj+xFAAvumNc6Jx1v2O0/TNCcT67FG73vierRnnjxPNzKch4nXaRPdIOHtuuGaubBx+Z2wOhQXV+HLCGNxBMFrndSkrzPZOmY=,iv:rNwGR63qMNV9mi2MtCjRXP7P4/nzRx7UuwX5QT6QbZg=,tag:gPZAiK+Fo5/Y+iaka0N3Dw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
