apiVersion: v1
kind: Secret
metadata:
  name: secrets-forgejo-runner
  namespace: forgejo
type: Opaque
stringData:
  RUNNER_INSTANCE: ENC[AES256_GCM,data:dHnr0XmCPFRJFXG+jSbsu6w1r6J7JVnLFA==,iv:Tv2KAcAqS9GSbwd/6ppBOjSqYx0AP+qWTCFlEjKjrrg=,tag:SziWIcG3nGZ7Lv2Rb3d6yg==,type:str]
  RUNNER_TOKEN: ENC[AES256_GCM,data:KjyxxKtmsDepKVAmddfbMzEAeYvCqie6bRYFS/O190y1yAo+1nJLmxvS0A==,iv:dQohENA6dzRhqQZSTdV5Bk4uTJKKsAzSQ+Nw+tkP7Zg=,tag:bHL8hXGyxZ5NXdN7xrJVZw==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUGYzdVBWREd3YkNEcjFa
        L2U1NDNsQ2x6VWhhVitRd05udzdHejVlRVVzClhJV0d4L0JYUk1DSVpCT2JOc3Jr
        bmpkYTl5aEo3Y1hNRlFkSkZqNlhraFUKLS0tIElyQy9NQm9NZGorMFVGd0svb2Fm
        OXlQa1lDZCtuK1g4T1VGZ0dOUHQwaWcK1/H2/pDFoymgLC35yx2lPN0NaYG879gM
        3iO/UNpc7wbeidP7HU5o3O+AAxyenuw9AT0oYOEiE64IJf2OZeA9PA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T02:10:16Z"
  mac: ENC[AES256_GCM,data:kwmssPblij1cU18rujKJUpn1KKmxkiQVqCaOUag9fEdT0rKlCvbELPssfQk6IS4b6XN+BdyCyfd15BIoL+OmSYFFrs2fu/8w0BZTtN7Opq7Ldc4USfkLVOryue1UHZ5EnBcB2Qcz0r+Wvbhxp4uZT4DtT5sLlHoWjQ8FY5YrnOU=,iv:SdPOUezm3jFMzV7IeVY1J7+TYiLlxhijlN/8Xlknecc=,tag:DqVPG6YNL3sGNwdY8aNzXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
