---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: layertwo-website
  namespace: website
  annotations:
    kubernetes.io/ingress.class: external
spec:
  endpoints:
    - dnsName: layertwo.dev
      recordTTL: 300
      recordType: CNAME
      targets:
        - layertwo-website.s3-website.layertwo.dev
    - dnsName: www.layertwo.dev
      recordTTL: 300
      recordType: CNAME
      targets:
        - layertwo-website.s3-website.layertwo.dev
