---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: s3-layertwo-dev
  namespace: garage
spec:
  secretName: s3-layertwo-dev-tls
  dnsNames:
    - "s3.layertwo.dev"
    - "*.s3.layertwo.dev"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: s3-website-layertwo-dev
  namespace: garage
spec:
  secretName: s3-website-layertwo-dev-tls
  dnsNames:
    - "*.s3-website.layertwo.dev"
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
