apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-metadata
  namespace: garage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: sunbeam-iscsi-csi
