---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compress
  namespace: garage
spec:
  compress: {}
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: garage-transport
  namespace: garage
spec:
  forwardingTimeouts:
    dialTimeout: "30s"
    responseHeaderTimeout: "60s"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: garage-s3
  namespace: garage
  annotations:
    external-dns.alpha.kubernetes.io/enabled: "true"
    external-dns.alpha.kubernetes.io/hostname: "s3.layertwo.dev"
    layertwo.dev/publish: "all"
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    kubernetes.io/ingress.class: external
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostRegexp(`^[^.]+\.s3\.layertwo\.dev$`) || Host(`s3.layertwo.dev`)
    kind: Rule
    services:
    - name: garage
      port: 3900
      serversTransport: garage-transport
  tls:
    secretName: s3-layertwo-dev-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: garage-s3-wildcard
  namespace: garage
  annotations:
    external-dns.alpha.kubernetes.io/enabled: "true"
    external-dns.alpha.kubernetes.io/hostname: "*.s3.layertwo.dev"
    layertwo.dev/publish: "external"
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    kubernetes.io/ingress.class: external
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostRegexp(`^[^.]+\.s3\.layertwo\.dev$`)
    kind: Rule
    services:
    - name: garage
      port: 3900
      serversTransport: garage-transport
  tls:
    secretName: s3-layertwo-dev-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: garage-s3-website
  namespace: garage
  annotations:
    external-dns.alpha.kubernetes.io/enabled: "true"
    external-dns.alpha.kubernetes.io/hostname: "*.s3-website.layertwo.dev"
    layertwo.dev/publish: "external"
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    kubernetes.io/ingress.class: external
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostRegexp(`^[^.]+\.s3-website\.layertwo\.dev$`)
    kind: Rule
    middlewares:
    - name: compress
    services:
    - name: garage
      port: 3902
      serversTransport: garage-transport
  tls:
    secretName: s3-website-layertwo-dev-tls
