---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - garage-metadata-pvc.yml
  - garage-data-pvc.yml
  - configmap.yml
  - release.yml
  - secrets-garage.sops.yml
