apiVersion: v1
kind: Secret
metadata:
  name: secrets-garage
  namespace: garage
type: Opaque
stringData:
  GARAGE_RPC_SECRET: ENC[AES256_GCM,data:wAs4pPbQ16PS+kB6G+YAEIuSN/i/4lEvZHEUztI9lmwfGVLYz3DryLzknm1svIUgBfFcaJ7LdBaWpVK9zlLpJg==,iv:/tvLKc/KA6Pweqyc3wa2EGm6Frj1/wupowmTiU4tKIs=,tag:CufEDYe0gL2XRqr9Fo0S/g==,type:str]
  GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:hsN6XCyLaDIrIYm3RgURw6nD/GDyWUJGAKftCrz69d2PDoESbKHFLNugwk0=,iv:PZTZnhhFtTLiANOQg5uDzzbanii4bY9j13HPezg7dc0=,tag:mbIuc3FmW0OCZI0kFnphgw==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeGhMVys3TTNjUkU3ZGlS
        YkNYUkpMcyt6d3VKZ0FiKzMrRnZiSWNIbnpNCjRMaHFXekdsbUx5ZnA5V29BeUpL
        VWp3RW5uZmF2MTFhbmk4L09VcGluUkUKLS0tIEg3Wm9XcUdVRVB2Um5uaEpqUFRO
        Wkc0d2dibUc5ZDB4eEVDTGp6Ymtzak0K0QY+WZOZ3JHCyM6VoPahVTUi4+7XTAxA
        X+11VRIyb0vk+LomvvsYvIupnAvXnEwbtjxB/yHdf6XfNbYBl7ztvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T03:02:23Z"
  mac: ENC[AES256_GCM,data:iXi/IlqfkwZYpz+lAy4tnlSjRz+wuN+3iSly9kiE1IcbSRfqsAZ0nJclK7xkqcAdvNGuf7ifbbLLDgC4PI8D73DrlJ/HmNt0viXHXUH7lO2b6XmwRwnpi7sW6VwwV5CyWJg7oJGDeiOZM7Y8z2U+VJ1bkYmWo4NU2oPEkfJlbng=,iv:Wr6W9urXRpzFI9GY7HZMYSEYPnVSuJt99e+L3uIt8dQ=,tag:6FSiFHyS7F8vy8Iqdk3y8g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
