---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ldap-outpost
  namespace: authentik
  annotations:
    kubernetes.io/ingress.class: internal
spec:
  entryPoints:
    - ldap
  routes:
  - match: HostSNI(`*`)
    services:
    - name: ak-outpost-ldap
      port: 389
