apiVersion: v1
kind: Secret
metadata:
  name: secrets-stoat-livekit
  namespace: stoat
type: Opaque
stringData:
  LIVEKIT_KEY: "7ef7c6076c9d"
  LIVEKIT_SECRET: "8ee242261b08ae3af72366e1e7273aaae39327c23462b4ce"
