apiVersion: v1
kind: Secret
metadata:
  name: secrets-stoat-livekit
  namespace: stoat
type: Opaque
stringData:
  LIVEKIT_KEY: ENC[AES256_GCM,data:gn9CwaKJ8QZAT3u/,iv:TjvK8+gTFeYC8yfAsjaHyCaILjDanm+9nVdIQBqF+xc=,tag:I3nqA1sngGy9IpE28aXc1g==,type:str]
  LIVEKIT_SECRET: ENC[AES256_GCM,data:a2li2/Pl6fKrPeb7PUvT6mcgk9vFnDhySASvwu3NE/f1xHo5BfeY+rosLGG0AR+A,iv:dbiP/y0i31oXkK8HVvO3hk4MYM3X4gwEZwREEvaBcv0=,tag:TRW6lqwi9+ryQrb7uouhzg==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNyszMDRoSCtiNlEwaDB5
        d2dWMlo5cHozM2xSMnEzcUtmMVRPd2YzQ3lFCkhOT1lTZllnMzdaVzNTY0lZaHB6
        TXJpelBwcmdjbEZpdmRsaWFMNTVsWXcKLS0tICtNMmRUWlNTOWFCYlZWbi9lbjNy
        aUIvWk5wWXpSaWIySWtlaVZ2NnpLdlkK4c9vpKl6Th2P227avExJaAjqo3oasxAI
        /X2Mc5tc2IVDXmQNHizazStTp5JdytlR9MoAmj/wiTRnbClcFBbriw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T03:58:26Z"
  mac: ENC[AES256_GCM,data:JC2QEy8J+JzyqklA7esdYczRDZYKgGScEkXszn8gxEoI4HfylNKsDNyrlQYHCDhFxIUF0E9Sy0yMZTE8msC8p/PQkl3yLph/kVp+Pb833nak1q5et7PMmJO1wvm1qOhM87SM22QJ+NxzdfJBRVzX0/gm7dFVKW+GzEg+ui0jAaI=,iv:aWRA70FrL5MzEZ96LOSu6ZnheuAbNKVkPytkNo+Nebo=,tag:R1AkF4MOCL4FNyZ2VAu+hQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
