apiVersion: v1
kind: Secret
metadata:
  name: secrets-rnsd
  namespace: reticulum
type: Opaque
data:
  transport_identity: ENC[AES256_GCM,data:95XZmYVXvoJQKWCgmm7dK/NGJ5vt8NZaWuxzhhWfdPwxq3G2hrkg86guEjoHQa08G9rUpqFW9F5nKFKdobHSQy2Gxce7qulxS1roffJpJgjCEicPz9YjrA==,iv:+Ny7wv+JCh/fSz3NKrwPQdmEMn9YNG4+6ZiKmCezPz4=,tag:bMFe1/lJAb6wOmIwmo+/Fg==,type:str]
stringData:
  config: ENC[AES256_GCM,data:ll0/eREX3Y09oxs3ZXVyGqL6WHvGG5+xmUe4zF69TsAOQ9W4mywzaiIvKtvOQq1g8cALD+BND/1aThLHV5iNoW6lpW3X+k6X2ViyZM9qg6vVzoO4TRo5t/o/sRvth0sVzcNxYs1+BSAhpnEkmEPBNCIXTNz9lYEEto4K1gVPL9/XxR6NPhPoaAAR/wFgDae1w0N3DofCHfiIX8G1sfiVkJR/bFE83SsWHIT1FYP43Gl9HRhuRWEOEFtZEwpUO20WyckN7lH8qLAfouWVGq+rOCghB/zfkvTptdO2cT2ckS26WaPzb0RCnQxmRZoTrRSPZtH/YnF+57NLD+TUg+KM97dSeth28+WnDcZlk6aoBak1VAmemGgzGAfdtz3nhPoQYyIeQwxlWyaIZR8nIpy73LUsLynOVe1cWUtDOkmZJtDlMF3/Vf3VqSvOu5uqxROkgPhaAFOqkusL4vB7dwe2piaqGUhrdAD9BEstydeJTgHS2ws/eb0W1kiS+On2mlBKIz3ettc6RJciwp6pSQ9IMLJE4XtKaxsASZs=,iv:s2Owi1SE4Fl6PiqVJVcLmgwzzKlUDPBocZyKJEScq64=,tag:+1MDruO1MYmake3sOjRbxA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTjR6dFJxanpSYU9kR2F0
        ZCtCek52Uy9uM3dsamgrZFo1bk1MZGVEbFNnCkVKdGI1Q1J3K2Vvb2l2QVBOejEy
        d0JwNE9RS3NOQUU0elRMbldMMmxkVzgKLS0tIGNqNlhCanI3bUE1MTQ1QytoL1RC
        M1dHcXN6RzY0OEJsQ0d1amxDNjdXb0kKvMe+gA3HyRQDLbYWM27ifN5lWlDDcveu
        Cr7oaT2jib/gLALLrYJCTdeseUNZnPXBr4adiEBbKznxZQYf8SgnOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T04:38:57Z"
  mac: ENC[AES256_GCM,data:WbijgDKORArObQQvcAYLm4gedaGWsrDLn/B/OxsshoFVHSo5e28LxH/RePxoHyoZMsd+c4kUy1P5Sjdgfxg/ViIolKjulv/HkCG19MGSvcuXAv7qi3jx/ndwLo2MKynB7JpRNTk5ItMNIyryBuKVMaUNpdnhC40DM5bWTSvkINY=,iv:TOIjSr5S4ZJz4FIFQdnV6KARBi6gML4ifrgOAvk06cs=,tag:lwXtgKHljXxVObp8IQSh2A==,type:str]
  version: 3.13.3
