# TODO: encrypt with sops before committing
apiVersion: v1
kind: Secret
metadata:
  name: secrets-pangolin
  namespace: unfabric
type: Opaque
stringData:
  SERVER_SECRET: "27b54e9e4b894eafc3d255857b1e02a894c245b71a5d12337a9abe2ba2f63004"
