---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: open-webui
      version: 5.10.1
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
      interval: 5m
  values:
    ollama:
      enabled: false
    ollamaUrls:
      - "http://ollama.ollama:11434"
    pipelines:
      enabled: false
    websocket:
      enabled: true
    persistence:
      enabled: true
      size: 10Gi
      accessModes:
        - ReadWriteMany
      storageClass: "sunbeam-nfs-csi"
