---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: stoat-mongodb
  namespace: stoat
spec:
  members: 1
  type: ReplicaSet
  version: "7.0.14"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: stoat
      db: admin
      passwordSecretRef:
        name: secrets-stoat-mongodb
        key: MONGODB_PASSWORD
      roles:
        - name: dbOwner
          db: revolt
      scramCredentialsSecretName: stoat-mongodb-scram
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            storageClassName: sunbeam-nfs-csi
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
        - metadata:
            name: logs-volume
          spec:
            storageClassName: sunbeam-nfs-csi
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
