apiVersion: v1
kind: Secret
metadata:
  name: secrets-stoat-mongodb
  namespace: stoat
type: Opaque
stringData:
  MONGODB_PASSWORD: ENC[AES256_GCM,data:XGgFlW/Yw1kogc+snkrAF+9LaGqMEIPfG9IWxYjmHSM=,iv:41+h5E6imCEQjxhnPQY0ChTBkjLPLvaGMM7XFUnyFf0=,tag:RY2HXToTvBfjLDVR1Rh4cA==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV3ZkWVk4L1ZaVmhha0pt
        L3BmNG1Ib0xkRXdsTVRkbGgzYnFMbnBlY3pjCkJkU0lSbmZLd3Q0U2M0WWtMME9z
        V0ZlNnI3SDB1ZFN5TlJzc3NZR3Vqd0EKLS0tIDlUMFZBUmU4V3ZSeW9DdzAwYkVI
        Y3hZaTMrWnhERnAyY3Q5L3MrNnNNSTgKyzcq8AD8MSRJ6Ypb1+NY3WcJgxYMmcXs
        TyYxkUvsB/QNBmXlXw3GRhQPZvwGk7TION2p5WTcj+BMsQIXLGr30g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T03:58:50Z"
  mac: ENC[AES256_GCM,data:foGc6/fCtdn7U7rXkSWnPsOhAivyCklWc6Q4cIzcSHdRdaHlVOnAWC4lXt1lkSCvu167kwewXZHlzsrK4uGe8X1mu0eFgllbdpjePkE8g9B4xJbNbHy3Iq6qK2oN2t2Q066ee0LExezasl25dkFTT7kdxlgfNVZ12RO6gHCQBZY=,iv:4VaRVToLv/uDiWoecHTGDdkxnsd3O5E56/fmumfQBc4=,tag:1h8EbM/cd7HUgQG+Dj+1Gg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
