apiVersion: v1
kind: Secret
metadata:
  name: secrets-tunnels-broker
  namespace: tunnels
type: Opaque
stringData:
  PLUGIN_SECRET: ENC[AES256_GCM,data:9RNJfmi/BeTAlarCHHjFIIHqTxXJJlQ+QkujCzLvgJONyQvTiPWrnBXdkg+klQk+iPOF1ejmMsx1bpv1ox+zfQ==,iv:pnJlyL/1h8ZQ1TC0oBb522f/1ZANzJmyo3MiYVk3TO0=,tag:4Gx0zRYm8sl9JkBWWoS3SA==,type:str]
  FRPS_DASHBOARD_PASSWORD: ENC[AES256_GCM,data:SOK5ExNMMuPOq9kMBt/32tFx0RvSvikjxSvDhf2Ki3aqu3+NVqAvqcbc/QDd+OkeTWvposlPaD4feiGqgjXzUw==,iv:Q7PBvYinBLWbXrcoA4dlnSafFjKBvOsG3hCkDhP06SQ=,tag:nMfmNFnioVdKwD77Xk3JLg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERlFYTHRGb0NZZmxId0lp
        bWpwSm1KRDFQTjFxYjhRb2lhMVRPVmU3UDNjCmEvNzhLbXh6S0poUlpQUDhzNmlJ
        aVlIbC83T0ZWYktFWmNjbllOeUpHb0kKLS0tIDNORVhUQzlQem5XQWRkMThrV1A4
        ZGd3ajErSTFpNVBtaVM2STcrQWRxQzgKzp1wwTMS9zh459XWd8U9GhOvbbP2+wjc
        iOF7CZ8uyilIn4ZjsVaznJFxK6ocj9pR4D+b8lzf04u90wPP8bOdng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T17:24:27Z"
  mac: ENC[AES256_GCM,data:KdhRoC27omGglua8TV339ANnu8VnDY3PiSWctiOvTAptKujPGoBoxcJZ0Yt3H2HHbPuNDQCK4FA61fNxOCmdWNGKT+NlpHt7tyP+tM0arbbVept0/UaQvA4ky7wex2f8xiPTF8g/FjgrViMKE+RWMuWduljhxYh3R7//n7uMMVk=,iv:sd8Zly8MYAUHJF3Na2Gg8W38YdayjObjboxaGmQj0LE=,tag:h+HP8uiOUJx+dhaV3sKtqA==,type:str]
  version: 3.13.3
