apiVersion: v1
kind: Secret
metadata:
  name: secrets-tunnels-broker
  namespace: tunnels
type: Opaque
stringData:
  PLUGIN_SECRET: ENC[AES256_GCM,data:m3t6O32X8gLJ6G00Rvgt6XVkcSbkJv3RXW2GLdN6dqaUESNQlFw/7k7d2Q==,iv:dPmQfq2vMRkP4oBDmVrRb93NM7ljFc4jHhwGnP/bWPI=,tag:w1kEA75bHNnngkTV5PEgeA==,type:str]
  FRPS_DASHBOARD_PASSWORD: ENC[AES256_GCM,data:hM14b9rc2p2tIFFQJZ0DFAzc41bxVcJN/a/hD5TOSryqgkCEeCWMLjPqDg==,iv:QYwgD0RIuMAxbsC0p+AtmEYWVEYAblGlHsewN28TtrA=,tag:EgaZ+P9TpVGS8gd25IQMTg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTGNVS2l2VmcrSGx5aVo4
        V0N0bWZvTmpDME5sNG4rd1g2OEl3TUlVMjJnCnRmNUd4cTRhcGpWZEUvdFJsUlZq
        MXoyUHM3U3Jmc0t3SjV3VEs0amNVcFEKLS0tIDd4U3BYNVZWTlF4UFoxK2UwL1p1
        R3JWdUJQdFJacUZsdllzaElycWlvWHcKwEGFgzi+fKJETjPjH6mquf54zTY9YHu+
        LvqZAhfoe5SoZvTa0Nwp8Cnyxe/LfrhSZh7mDEKAzCoK7YTWSZR3MA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T07:08:20Z"
  mac: ENC[AES256_GCM,data:cCeesFKTaZbv018nQZqQJpWmmo4GQAf/rnn7kD7ot9J/Qq95ZkYTslUXT2j+twT6+ntTRKf/xyoMjWLqiUo2TjXfUuRTBcZGySYVbPDf2OsXac/FAkLJJR7l0deLq1KldU0yOGece2od1kYavLypbQ/Chr0sUoXyeT8xiNLCAw8=,iv:ajhzEDZIAhY+hdwHK27hq0x1YkYkBB/Yy+CwUw4Jrv8=,tag:DkX9oJaF/8wNakwk1lrUDQ==,type:str]
  version: 3.13.3
