---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pocket-id-backup
  namespace: pocket-id
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: cnpg-pocket-id
