apiVersion: v1
kind: Secret
metadata:
  name: secrets-tunnels-oidc
  namespace: tunnels
stringData:
  clientId: ENC[AES256_GCM,data:AxsmCow0E6dx0IT95ya//+17kRtGCndSsn259OhDDLJRFQo5,iv:ab6WeDmPPz0xIx4LxggXpkNnORFAzaPl5CDPnU+uXys=,tag:cyjXUHoB73Ed+nLl4IlLDQ==,type:str]
  clientSecret: ENC[AES256_GCM,data:i1ZngxIK53YL+mj2pIHxsW4tkrFHz7i/dcPrghQESXU=,iv:8sSbnd7PkS53tD/ajSF9ahVGvoccWhql9Qc7uBjXQsE=,tag:Zcfz3MRiMoKJjMw9W9gQcQ==,type:str]
  pluginSecret: ENC[AES256_GCM,data:hRWHNFOFmudztkDWsoofkDXiwtGRC0a5NbgBF0xmXWE=,iv:WTHQ3lJPm7kSYF6pxEc2Qdz9MmbuE69QJD0SXEILSSA=,tag:mnUu3nJmx+Drm+36O0jOHA==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbDhqdVFIcXo1S0cyUmVY
        cDlGSXFoT3dwM3hIYUZZbU9ieGIzWk54SzFNCnBkQmlaSlI5djNYY2RwaENMWXZL
        U1lnOTdaMDRXZWt0d0FRWWI1NWZaYmcKLS0tIGExSm51bEZYL0pGZG5vMkxWZkI0
        WVU5WWhGdEhLVkFMRlh6aWFnTXRIK0EKCFKAMoCDENZCxgDNnXZKNllc3pHy39w1
        M/9aO1OX22q0vRi5F/7KES3ijKI8N3TCI1YvH/fu18JkB5pF+hp4vw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T23:35:34Z"
  mac: ENC[AES256_GCM,data:rZ8B8flKUgmU932658uSe69D9CTLb/Nk7jIiF0KqpSugBBj4FIYU9REkTLH08Zt1dDzNtycoxxyFJ6vxuHe9Us7OL4kN5+H/Ctaf04MVgBcKQGuLR1EQuiY1mhfDOO0WIUtXbj+lKtRs9P6fMrmk4lDniQtM9ucVzDXH5gge0FE=,iv:+juIBtAPzeUGXHYUnhJUoAyK8SSSh21JcBNDakmhYDA=,tag:IHCMnP4fVwNA2p8ukyMVMA==,type:str]
  version: 3.13.3
