apiVersion: v1
kind: Secret
metadata:
  name: secrets-outline-volsync
  namespace: outline
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:ihfvb81MLn0vZf6YQUqnY6EasMIhW6lPUOfdE+FYacmTtMWuqNbJNM2zBregKy91td8FB44BDelWk/DsdjeNVmsvA+aIYvYlVsSykgp9SIfHbqoMRRQcFAp1LmlbrdqbWw==,iv:G+uOtY69VW6gMFIB7t7nPgC92QeeEwfqmk1/wLOsYxs=,tag:007JbenJ8mPGreVIKTPwGg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:0M85iCOlP2Mn5u459bmtWKaWkLKsCf9mhLQsJYeL+zWMSmz0NOve4+Y8+0Z/VneYmPN2m7+QM4gSwdAVx4LeYQ==,iv:thGLlvdb8RNts34nrUhQWnV6zImiJk/uzqOLD83A6Ds=,tag:vNcUx7U/pmsN/4eqH6RaPA==,type:str]
  RESTIC_COMPRESSION: ENC[AES256_GCM,data:/kSg,iv:L5TS107x8I12MMT33E+riPExg0NxGrRYkIM6lyY97k0=,tag:+yxfBX02iqaKQ1sLV4M8ng==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dhN3x5zRMW65YI0wbeC8EhbVSyaGDDgoUdGSlSRtijc=,iv:ab75uoMf2UrOrawJLLkKnEyevoBFINkZWpS5w25u+g4=,tag:9hmFm0BtbbEpiI6l+5+WmA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:g02vO9jK0h2jb7EHy2yFxdDmmcv6TUL0s1ED09cLvdNq+OVhRTG60oQ1wtTbSUHvMSGxpGlizpGsN9s8MSWstw==,iv:qn6yjQTKCxJVZ2cuBvhLn3k1M9y7m7KrvUpz9u+rCt0=,tag:Qvjl9R0fzIoCUgg/MIAvNw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcTF4U2hqcnhDbWZMbGcr
        SWNCRGFEYW5WdTJiblJVQk5lV2ErcWNuc0hjCmg0dWVrTlYvZFg0d3d2N2ZaczZD
        VVFtUkZuNi9XSmJ5Y2hmQUlhRUtaa2MKLS0tIE5pOGZrYk9uTFE4bW9CblNCT1VI
        RENsUzhZKy9pZGRDMDhnUjRxWDZ2WjgKY54/Gqm1JOwuM+lqa/LK9MlTGglK8ylo
        B4z+H+/Yk8BEgPC90qyE9KMkpxWv3bwNfXjb0Nz43uK4Kw4pDikG3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-23T16:52:55Z"
  mac: ENC[AES256_GCM,data:YYbppyW70roy6e4+zTqPC87uLHUj9a4mZssBEL3rkVkKCcQFge14/n7BPaAS8YLTyKRZK2pG53+jigTzooWVAeBemwlltYc4NlIciYKHNH5rLvwnjoQwFvS7AxsuOaIqwV9IRIAUaTeMYSIS8iunjQYf4hwzS7IPtriwo4s/eck=,iv:NsvkH+vPMcRB63MteYfEbGSlt/8YwkUkX0gKbnD7Rh8=,tag:XsbcQsAp41wVg75DAOeU9A==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.9.2
