---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
   name: outline-backup
   namespace: outline
spec:
   sourcePVC: outline-data
   trigger:
      schedule: "*5 * * * *"
   restic:
     pruneIntervalDays: 15
     repository: secrets-outline-volsync
     retain:
       hourly: 1
       daily: 1
       weekly: 1
       monthly: 1
       yearly: 1
     storageClassName: "sunbeam-nfs-csi"
     copyMethod: Direct
     moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
