apiVersion: v1
kind: Secret
metadata:
  name: secrets-smtp
  namespace: vaultwarden
type: Opaque
stringData:
  SMTP_USERNAME: ENC[AES256_GCM,data:PBRScHAIgC9d9w+vCRRGg2jf5Buc9eKKKhI=,iv:FI8htpfONwycY3VVJQOqKwbzqhEUSxYQjbxQisGa1ow=,tag:Y60SMMa31jcNoyM4C+AtgQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:oAVIxwWd/EYWaMAg5dVHww==,iv:cAvsVKz5BJHfnz42ZDXjO/7S0wMSl7W9BrSDfltOfmo=,tag:ncp1/hcUvNCPBEKVAON1Tw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNE5BaFZFSFdDSW1wRjU3
        S0NMUGQwWFo2YkIrZU5pdWcwQWZBd212MGo0CnJ1VFpRbXhDSm1pY3JUNEhIOGwy
        RUtXTTA2SE5yY0lpaTJzbVBQYjRZTTAKLS0tIGR1YkFEQ3U1UUZyU2JrSW1paVJ1
        TEcvcWZOUERtU2tuVXMydkhwREFzdEkKmQq3MOI9/M+4fBpuwlU6K+4Q2C/Fijeu
        Kbiqguf86v5bdpV6nUmJBeH/zbOyQgs6yAzRJx3+HLBSKKyI4vF5/g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-14T03:57:05Z"
  mac: ENC[AES256_GCM,data:iEz/m/XBh2dhzy/GtVoZ8zkn66KzfR5E4YT0StuNM1UxrwVFESP5scXXbf143bFQdMYOXmkMGYF7Ikyg2YLLkJ04X9O3GaeW/HLcisVW8VWTAVV08emdelLZR5KKbGk/69+06elKnEgXI5KdwkUY4qK4MiPiLPH6eq66UewiYHc=,iv:7RGVnOByfTbvO2SMAHzb1NHlvtg35rBKdkqOLb4hF2g=,tag:TjEQqHoZxZdkLgEa0NrncA==,type:str]
  version: 3.13.2
