apiVersion: v1
kind: Secret
metadata:
  name: secrets-vaultwarden-admin
  namespace: vaultwarden
type: Opaque
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:1uCCAqB5Pex5CRSQ8jiGtZW57dLV0eskXh64y4f9qWYQz95nOMrDO0/QQ8gRPuJzv29vyL9Csw2Xkn6g+khKJB24o0FdXOxHSO/1B7SGEa1WxGpEJzyV8kNJXK59keQ/w40D9DmXv83Y4hEF/WEMcTvP9eMXeg==,iv:j9nsQiR/i45amLgxKX0jxW+kgr5vajK0zf21wTcBWos=,tag:gGeGDzd7QqiaXxy4wc2Uhg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIR1lybmRDUlRyRjRaRFJU
        ZlJkRHpXSmk2T0twSkJTc09vWWxhdmRGNUZJCmFFYWQ4QWtlVU5rNVpyUlB3VWl5
        bFU2ekpyZGgyckJ6NHN2NWNObjkwck0KLS0tIG5pNjUxeTFBVDB3WDdCUWdYVTNF
        TjVsWWN6Uzh4UUM1MGY2dnluaFlHdXcKqTSnkBD/uZZLpywfdPwlMGEySPNzvAxN
        0xD+XEOu+NklCcP2/vR7wx7E89Cscch1CVULyg1M36gX53QuT0Qu9w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-14T01:14:44Z"
  mac: ENC[AES256_GCM,data:ZBzxrWhJboURj5KWaCjOnXhGEiDe2SyonT71Nt0RpE5fR/7r59CFcl25KpLTR6w6dmL+DZRmYqAWlHom9qP22w+Kj8yKuPkDnlEUia/qlaeFdYf7vCO1V/t/B0CIpQCR1y/ACxcSr4LEcKRVnmCISxzAAG/5rIw+ArROcmWnJYk=,iv:1MJesbE9/3B3717oolYOcEupqNtXaStW2LK+Ku0gMw0=,tag:C8Mzdk8tRBGeHQtKX0JGZQ==,type:str]
  version: 3.13.2
