---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-cloudflare
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.15.2
  interval: 60m
  values:
    logLevel: debug
    interval: 2m
    fullnameOverride: *app
    provider: cloudflare
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: &secret external-dns-cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: *secret
            key: token
    extraArgs:
      - --annotation-filter=kubernetes.io/ingress.class in (external)
      - --cloudflare-proxied
      - --cloudflare-dns-records-per-page=1000
      - --ingress-class=external
      - --traefik-disable-legacy
    policy: sync
    sources:
      - traefik-proxy
    domainFilters:
      - layertwo.dev
    serviceMonitor:
      enabled: false
