---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zwave-js-ui
  namespace: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        type: statefulset
        pod:
           nodeSelector:
             feature.node.kubernetes.io/zwave: "true"
        containers:
          main:
            image:
              repository: ghcr.io/zwave-js/zwave-js-ui
              tag: 9.29.0
            env:
              TZ: "Etc/UTC"
              LOGLEVEL: info
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 15m
                memory: 150Mi
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            port: 8091 #*port
          websocket:
            enabled: true
            port: 3000
            protocol: TCP
    persistence:
      config:
        enabled: true
        storageClass: sunbeam-nfs-csi
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /usr/src/app/store
            readOnly: false
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_51501310-if00-port0
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/zwave
