---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zwave-js-ui
  namespace: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
           nodeSelector:
             feature.node.kubernetes.io/zwave: "true"
        containers:
          main:
            image:
              repository: ghcr.io/zwave-js/zwave-js-ui
              tag: 10.6.1
            env:
              TZ: "Etc/UTC"
              LOGLEVEL: info
            securityContext:
              privileged: true
              ulimits:
              - name: nofile
                softLimit: 4096
                hardLimit: 65536
            resources:
              requests:
                cpu: 15m
                memory: 150Mi
    defaultPodOptions:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.43.0.10
        searches:
          - home-assistant.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "5"
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            port: 8091
          websocket:
            enabled: true
            port: 3000
            protocol: TCP
    persistence:
      config:
        enabled: true
        storageClass: sunbeam-nfs-csi
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /usr/src/app/store
            readOnly: false
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_51501310-if00-port0
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/zwave
