[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cloudflare-ddns"
version = "0.1.0"
dependencies = [
    "cloudflare==4.3.1",
    "requests==2.32.5",
]

[project.scripts]
do-dns-update = "cloudflare_ddns.main:main"

[project.optional-dependencies]
dev = [
    "pytest==9.0.2",
    "pytest-cov==7.0.0",
    "black==26.1.0",
    "isort==7.0.0",
    "flake8==7.3.0",
    "Flake8-pyproject==1.2.4",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-vvv --cov-report term-missing --strict-markers --cov-fail-under=100"

[tool.coverage.run]
source = ["cloudflare_ddns"]
omit = ["*/tests/*"]

[tool.black]
line-length = 100
target-version = ["py313"]
src = ["src/", "tests/"]

[tool.isort]
profile = "black"
src_paths = ["src"]
line_length = 100
