apiVersion: v1
kind: Secret
metadata:
  name: secrets-vaultwarden-oidc
  namespace: vaultwarden
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:MoFX/AeuGn9Xb16nh3sZXl+THZZ42RNmMeJUUPIqhp517tFe,iv:IMiSYFBHzwK5aRqcha+FcPgufUm2wAqxFQ81F4s+byY=,tag:gHoLxNRNi4SMiLk47t2JMA==,type:str]
  client-secret: ENC[AES256_GCM,data:RVqaSNNbFjpq5t7TkWKgkdbWoTLOaiC8fLlPxy4ng9w=,iv:k2JTUzsbaKXyg/C9edEMq3hIS5VugiUftzcpu4YkHtA=,tag:Pckw7eaRJOsnKcPy6doSOw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeGFHSjkzQTJFZittbXZW
        N21SSC9FQ29MZ3pDWS90MHUvYVF2NThpdzA4CmQ4M1l5ZDhaaTQybEhoejcvMjV6
        N0o2aXZCV3ZqVnhRQlNsMXJYSkROVTgKLS0tIFpLdFZ6NnpKdTZUS2c0RG92Smt0
        L3Awc1F6dU5mQnNaZlpBN0RIVXdxZmMKR2Ct+sdBc+TB3OBynoV68WUz9Ice5plc
        Yy+exm9n9WbcERdNNK3z8/7QrZC35qr2bTf+TCLaJIhDnt3V0wK/9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-14T01:24:00Z"
  mac: ENC[AES256_GCM,data:3vc6yEEVChL5vumygCZ4CzLpRe/WJQCX8jGk11DeGqASyQFPOC+xKSbmIa9mNZF9H2wpxoIoFLIdR1teJPoGsGqihq/1kATEhehKUSpy2K2lQK8Sf9IIpoi/ZUKp1dZ5NIWpI614wFZsTroxgriiSF/tCIvcl4O+KPLMD4g8lO0=,iv:/t4TesSZBopZJq/zHu8qIcPDPeriWAIx5ecr6YIXASQ=,tag:gv7RqWf5szGep5ccUNug+w==,type:str]
  version: 3.13.2
