---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frps
  namespace: tunnels
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      annotations:
        reloader.stakater.com/auto: "true"
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault

    controllers:
      main:
        type: deployment
        replicas: 1
        containers:
          frps:
            image:
              repository: ghcr.io/fatedier/frps
              tag: v0.71.0@sha256:cd8b947ba61678b200baa4f71ccc33f3c52e4e2cc0059700ba3b8354e36af7c3
            args: ["-c", "/etc/frp/frps.toml"]
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 7000
              readiness: *probe
            resources:
              requests:
                cpu: 20m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]

    service:
      main:
        controller: main
        ports:
          control:
            port: 7000
            protocol: TCP
          vhost:
            port: 8080
            protocol: HTTP

    persistence:
      config:
        type: configMap
        name: frps-config
        globalMounts:
          - path: /etc/frp
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
