apiVersion: v1
kind: Secret
metadata:
  name: secrets-tunnels-frps
  namespace: tunnels
type: Opaque
stringData:
  frps.toml: ENC[AES256_GCM,data:TFZoqI84L6oU/lIFuzL0r1ViWgTnetrPYpRuXfwxn3RgJmMQ+qMI98WOKKqo0/wQKpZy9OT5ApP60e0narC0Ka44sfHtSnoZNjJvNtggJXCbI92oEyZKkf6fhaaZrFYvza7cjChZNsi37qWz8B7yt/GUY1ALaS61UHLImS2Rx9IxtGvyElPCVony1VungPiHEm1xxhbUvxMSCuseP1AEwc3thCnlcpvQZjAWOel8Ndq/4zpNLG16edPgCrq4ygGuziYcQUw1pPftYsqIZkx1DhiMMUqp4gRM0Am05BwSkEGcwKOGy9IYR9F8RApmUJypEcUBXhOLsxss/bWglwix4pa9QmJZwmIwXeH4WlUsqYDoAo3w833HwgeBM/Xv4F2IqpNb5ux2EdQA3JLq3eHR9jVpzhMQ6OEpiXdL09fc08FdkI/7x2tFiTAuWgojWafDQxQb7+LQxj1r+XCs2DoGKCrJsMelHuAoy+rSlETulKS3upkSEhODch4801zy5+3evF+D76RG5xcnS4x2W/E3DN9zFYVNkoDLWlARRPmp7f4QEj1ZY4aCOwARbV3HCL0RgLz4Dp3ZmVFVH+b0yfCrzb4qX0YBD5YOMvz1euM/v0nQypdCeBWy2SrMwdKmhqwKM8L1KLjpCtZQn7BN3yNJs3NvPgry3NZNFd8rptnUpjUnrIWYfqZeMYb1svmo7ihzLe+UUmNwZrYMuxfjcMLHN21ypswUEAiLUp4TeaszbmvT7f1CvHO9v23rke00EgeCDJ1yA8EiM+UPLfhagfer76fNmMLr7oZj2XOsFhTER34Hq1UHack2022suyiIIZjXxS5rtTizbAVZ73nv6EPWdlE3W58YSiVfaCAGz1cFUD8H1OHcBtTsr23yOd8IVfzdqFVH/upeydlV4beghRWzYv5/b+xGIEdIcm7LU6AgROOVQ5SOQ/Ve9U/c8l8ZcxAB9EspirXIi86LvWqVvuMn5+eGtmMk2L7mWUpgEPAuz68bqzEXQQNW,iv:xPgdYnPqVc2tANse+EpIQOcBsf4Iagqv30RrIDmcAhE=,tag:BmGWMTKXHIu/duT+EM6ozQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNWZzdndnSiszcFgyQitm
        WmZQZm9teWo1OHVySHdyb29oK0dpOUdwRlFvCnVjRmZ3N0phT094bDBkTnZWd3kz
        cGJpVFNHWDV1WXJQUS9LQUpmNmJUazgKLS0tIHdKZ29paENSUDhFYXRQeWl3ZDFO
        ZjFEbWtLK0xSVG8vMlFCejRkT1VsNVEKkEFNVNv/wFJU6sJzPJKRMcZO03RVtX9F
        jh3K87N7A2RgCp5D2T05AHgHMVIf4SrEtMhxpaz3kN94KyCVxTiDQA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T07:08:21Z"
  mac: ENC[AES256_GCM,data:vw2p+F6pqXZuRbQzMcu5mgouz/6uTFUkk6IwiEhwzig/yonkJY/u7O9HNMEAIJ0Lg1ZQ8Pwsb9J/KnwxQcka2OeGZS2oN4IAuGfh0XelFefLrL1CPv64/HuljTI4uj2j/P1Gd0dqwg6T9CBsWHrDUp6K+iQWVCPxzy4/eNtOk8k=,iv:2SIBb0LzWBQU3/AoRrFCbqyH+M2tyaessQiPuqGheCw=,tag:SMg5YuiJGMqn2K+vwTmjuA==,type:str]
  version: 3.13.3
