---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: traefik-system
spec:
  interval: 5m
  chart:
    spec:
      chart: crowdsec
      version: 0.21.0
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
  values:
    tls:
      enabled: true
    config:
      capi_whitelists.yaml: |
        cidrs:
        - 192.168.255.0/24
        - 192.168.2.0/24
        - 192.168.4.0/24
        - 10.42.0.0/16
        - 10.43.0.0/16
      parsers:
        s02-enrich:
          whitelist-local.yaml: |
            name: crowdsecurity/whitelists-local
            description: "Whitelist for local network"
            whitelist:
              reason: "local IP"
              cidr:
                - "192.168.255.0/24"
                - "192.168.2.0/24"
                - "192.168.4.0/24"
                - "10.42.0.0/16"
                - "10.43.0.0/16"
    lapi:
      env:
      - name: TZ
        value: "Etc/UTC"
      - name: ENROLL_KEY
        valueFrom:
          secretKeyRef:
            key: ENROLL_KEY
            name: secrets-crowdsec
            optional: false
      - name: ENROLL_INSTANCE_NAME
        value: infrastructure
      - name: ENROLL_TAGS
        value: >-
          k3s
          k8s
          k8s-infra
          k8s-infra-traffic
      - name: BOUNCERS_ALLOWED_OU
        value: "bouncer-ou"
      - name: AGENTS_ALLOWED_OU
        value: "agent-ou"
      dnsConfig:
        nameservers:
          - 192.168.255.1
          - 1.1.1.1
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 250m
          memory: 250Mi
        limits:
          cpu: 250m
          memory: 250Mi
    agent:
      acquisition:
      - namespace: traefik-system
        podName: traefik-external-*
        program: traefik
      - namespace: authentik
        podName: authentik-server-*
        program: authentik
      - namespace: mediabox
        podName: jellyfin-*
        program: jellyfin
      env:
      - name: TZ
        value: "Etc/UTC"
      - name: COLLECTIONS
        value: >-
          crowdsecurity/linux
          crowdsecurity/traefik
          crowdsecurity/base-http-scenarios
          crowdsecurity/http-cve
          firix/authentik
          LePresidente/jellyfin
      - name: PARSERS
        value: >-
          crowdsecurity/traefik-logs
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 250m
          memory: 250Mi
        limits:
          cpu: 250m
          memory: 250Mi
