apiVersion: v1
kind: Secret
metadata:
  name: secrets-crowdsec
  namespace: traefik-system
type: Opaque
stringData:
  ENROLL_KEY: ENC[AES256_GCM,data:Wy2Wa3QWsD5/45bblAa8WXlQMU7UjqXB4Q==,iv:quHepQbNYDglqzkk3hSoXJFy8la1l/BMDaE/Ef4ljAA=,tag:pLHEe6iHOvS34lektgPm+Q==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZXMzdUFaV0ZOeGdVL1pk
        ZFIrcmt6MTEwUEM5YUJUMUdGU1o3ZVhvRUd3CjkvcHFWVDlIK0pHYmhhY25nM3NU
        d0wrTWp0UVJYMHByd2FrWEd2STRoQk0KLS0tIHdQR3o2c0h1ZjM4UnB5d3o3SkFi
        Rzl5bnJaUUhNWm9GSXpDT0Vka1d0VmcKh7W03XhMBEcXw3BcsmeVEVnppTOSxkmF
        uejdHCSPJg1EMpg8qK6JgZw2z3ruD5KuRxIbyO34PrmhgSlQ500m6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-20T02:04:26Z"
  mac: ENC[AES256_GCM,data:GOBdqq2fNZu18msRq9bJZ6+au8Kg8cldR+wp/qN1mA6cBA/sO0RhiLFJ1m6/pAYXQhg3ctyJHxHxzv8hlmEvD1l9FKbQlQUDlodqBICJnuPkll+fpPskDl7lJh5barL3vQQCKUsgUzgN2eN82ErrMB4/IPP1ryEqHQEcYlRSPTQ=,iv:D8hz3QvtyUGH4prf+BpYIhwJjXGyaCJkQKtD10TCac4=,tag:ZkI6a8emj4n8gXNVN1GpYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
