---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-home-assistant
  namespace: home-assistant
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  imageName: ghcr.io/cloudnative-pg/postgresql:16.13
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: home-assistant
      owner: home-assistant
  storage:
    storageClass: sunbeam-iscsi-csi
    size: 4Gi
  walStorage:
    storageClass: sunbeam-iscsi-csi
    size: 4Gi
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    nodeSelector:
      location: home
