---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.15.3
  interval: 60m
  values:
    installCRDs: true
    global:
      crds:
        enabled: true

      resources:
        requests:
          cpu: 10m
          memory: 36Mi
        limits:
          memory: 128Mi

      enableCertificateOwnerRef: true
      dns01RecursiveNameservers: "1.1.1.1"

      leaderElection:
        namespace: cert-manager

      prometheus:
        enabled: false
        servicemonitor:
          enabled: false
          labels:
            release: monitoring

    webhook:
      resources:
        requests:
          cpu: 10m
          memory: 18Mi
        limits:
          memory: 128Mi

    cainjector:
      resources:
        requests:
          cpu: 20m
          memory: 72Mi
        limits:
          memory: 172Mi
