apiVersion: v1
kind: Secret
metadata:
  name: secrets-stoat
  namespace: stoat
type: Opaque
stringData:
  VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:tDItzaZdZIyZG5+F4MFeIL15T4ySbFRqaS+cmzkKyNHc09SwdHpd5QSqvWHKT1JHHgQizC9hl2oeKqkG2ADs3eqktEqjVtK3nTQoUZvnBAe2q7hpu056kCkpcNtXdqpFOzzt3uo/bfT0550mLo4vDIAUWZ2BAWZeb9TKq2ta6rkRJR93pItKx4P1YzKdUOZ/48Dsb1HAjfVnU5NE4D4sOlYZ4hYU1nQVhaIcef0aHM9P0T2H4rPhdJr1zoD1lcd2q6/Hu+IY5pHBAin0upUBGAE33lmAppRFWTysC83+aMi/KbAsoUXd5sXApqD8N6gEYX8OEiYobdQBfIVnFFwgGBNNVrxaxFfa72jHCJkmbaIEHz0bV3NOGAbonE/rJtYqjGy9dYx4DeioaC7DKmYa,iv:jKdIfgk/XWlz/KRyLvBmGvedcFXX29lTJoUWOr95DOc=,tag:G/sqdFGQjJMlBrSYjO1jug==,type:str]
  VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:DnQk9cFwU6AhBjOk3Y/Y1O2X9vnEbdofbQPgOenoqb70AZip/0Gg/gA7i6DMYMonopDub387bzah1Yktql7YJCapRsyPVo46KPsxQE+JdmfX/WkauebU,iv:kVCTkubNsXRQ+AK8pUSdgnK+d8Q2cm8qyRWesfXKAnY=,tag:cf5SUF0GxCoC/WaweX6Hqg==,type:str]
  FILES_ENCRYPTION_KEY: ENC[AES256_GCM,data:zYIenB8cXuLFN3HcJY4YgNePkVUPPGZ4DQviYJuVRYUO1pOwuEWue5Ksn+s=,iv:5M8vdGPR89wnvNAE6kmXPGAZ9IAYhf/B4KDNCgxxJfY=,tag:fV0KDWNyjmr4CNcQsTXG6w==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YXZ6b1J0ZGhQRlIxWjBq
        R1hiMWJGN01lM1hXWkZ1eFFtSmMvOWRWU0dVCkJJU3U4WnBaZGl3REhlUDlOMFBv
        b0o4R20zdStaYlRyV01jQjEvdjNIc0EKLS0tIFg5T0ZaaG1xbUd5aGh2UlpKRWVM
        ZDRRY1crRWpzaXpIc1ZKQUhQS2FkUXcKim/yl0HcifXrp2hy9mRcIXiZ/p4kqHXo
        vscgX9gfApSxwfElVHuyJtIcVEg3kS5Gp25gc/4ydO5skmjHKhwOWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T03:58:14Z"
  mac: ENC[AES256_GCM,data:Gx6swqtkKRKxmghWLaVz4fSmuERISiFo8kq7Bnpk3IvCfmPTd50vvk9LX/YfC7WfBDyWd26sS2ojNdFuNqoKJXt4lSPhxu3mxWWzyGTcN3BGRS6QBUmwgPzqWlxjcUWmx00qzptuTcauIFDoZc2NgKhUl0y0yWi5BNNhLJRWP9M=,iv:4YGkNT4SyqD5zboh00tuIAB3zjOtgtRWnukpoC/hIfc=,tag:2rBDf0GJfUaypKCkxXbQVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
