apiVersion: v1
kind: Secret
metadata:
  name: secrets-stoat-revolt-toml
  namespace: stoat
type: Opaque
stringData:
  Revolt.toml: |
    [hosts]
    app = "https://stoat.layertwo.dev"
    api = "https://stoat.layertwo.dev/api"
    events = "wss://stoat.layertwo.dev/ws"
    autumn = "https://stoat.layertwo.dev/autumn"
    january = "https://stoat.layertwo.dev/january"

    [hosts.livekit]
    worldwide = "wss://stoat.layertwo.dev/livekit"

    [pushd.vapid]
    private_key = "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUxvNDBSdjFzdktzN09WMzVTKzRjMUtNaWNIRHVKUG8yRGZhWFFDQmNvM1BvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMHdxZGVZZnBkVTUrUStWNkltMHFOR0t4aitYUHV4dDZDRTdNYTI2ZnMwaEF5d21aY1ozbQpqRGxRb1I0VFo3aEhERnl0TnZFWDROSmZWUU1KYmFocDZBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo"
    public_key = "BNMKnXmH6XVOfkPleiJtKjRisY_lz7sbeghOzGtun7NIQMsJmXGd5ow5UKEeE2e4RwxcrTbxF-DSX1UDCW2oaeg"

    [files]
    encryption_key = "KfDwuxBPKma7R4ZSKa8ddYwDeuQF6QHFPGz/xoEewAA="

    [files.s3]
    endpoint = "http://stoat-garage.stoat.svc.cluster.local:3900"
    region = "garage"
    access_key = "PLACEHOLDER_GARAGE_ACCESS_KEY"
    secret_key = "PLACEHOLDER_GARAGE_SECRET_KEY"
    default_bucket = "revolt-uploads"

    [api.livekit.nodes.worldwide]
    url = "http://stoat-livekit.stoat.svc.cluster.local:7880"
    lat = 0.0
    lon = 0.0
    key = "7ef7c6076c9d"
    secret = "8ee242261b08ae3af72366e1e7273aaae39327c23462b4ce"

    [features.limits.new_user]
    video_resolution = [1920, 1080]
    video_aspect_ratio = [0.3, 10]

    [features.limits.default]
    video_resolution = [1920, 1080]
    video_aspect_ratio = [0.3, 10]
