apiVersion: v1
kind: Secret
metadata:
  name: secrets-s3
  namespace: stoat
type: Opaque
stringData:
  GARAGE_ACCESS_KEY_ID: ENC[AES256_GCM,data:c1hwzyNxiozF5hDHMRaqei2Fo0vQnApLODM=,iv:PVgmyHrAQFNN+H1fQqBiUU7wA+6b7ihxVOyYaIAoPt4=,tag:ipcUCnSLbLKwQ4agcgZ8pg==,type:str]
  GARAGE_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:n1JmzykaxmevvHbesYXAFlF+ikxJ1RVoWsgmmj6lKDMOoe8Nt6+HUJg2AvkhP/6oEB6pJHTpoPYss7/SbGNK1w==,iv:AZhyViex+lDueRyu3ITUZMaCq2n1S9I4Tr6cQydDMMs=,tag:kV/vGAD/N1GyFqZEK2AmUA==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRHJWWVpMUjEyN243akhh
        NzdRQnlybTFXOWdQR2FxNjcraWV4WEU4cERrCitwQnhMSG5CTlBUZkJ1eHlXdFox
        Zzd6YTgzdEdGU29OdkVjamRROWFnZWsKLS0tIG9XckNHMW4yVmdTaGhlTTdLRnFz
        KzU2djh1WTQyclBIdHlhNGJ4c2dnSlUK/2GVkjb26xMAxN237CXu9A+iaJ/JhTQP
        x940NAZZqwe+ckApxF32kihpOaDUgq98brNyVyAFD+hpXoe9+qYHWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T03:58:09Z"
  mac: ENC[AES256_GCM,data:HkAy5m7zPcklr/QuIxxx7lOzKO/NBInOIyB8OqFVxofgZFugCE2b2wV8Jxz+4VT6SFQvoppUrKoOcaAfICa4lpQY9tNyduyrGDMnlWVErs2X7qzPNUq+kC3BO4ipE8LhGd4v/HtQQRjiqObC+bA/5CCmP2iKkAziM7cbhjP5/ww=,iv:lcrmhKA1Qma1fE3N3VgvLp8fogW/JhsB9CLNIpPYwcY=,tag:+lSYiPKN1dZ8/aUATlAPqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
