apiVersion: v1
kind: Secret
metadata:
  name: secrets-stoat
  namespace: stoat
type: Opaque
stringData:
  VAPID_PRIVATE_KEY: "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUxvNDBSdjFzdktzN09WMzVTKzRjMUtNaWNIRHVKUG8yRGZhWFFDQmNvM1BvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMHdxZGVZZnBkVTUrUStWNkltMHFOR0t4aitYUHV4dDZDRTdNYTI2ZnMwaEF5d21aY1ozbQpqRGxRb1I0VFo3aEhERnl0TnZFWDROSmZWUU1KYmFocDZBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo"
  VAPID_PUBLIC_KEY: "BNMKnXmH6XVOfkPleiJtKjRisY_lz7sbeghOzGtun7NIQMsJmXGd5ow5UKEeE2e4RwxcrTbxF-DSX1UDCW2oaeg"
  FILES_ENCRYPTION_KEY: "KfDwuxBPKma7R4ZSKa8ddYwDeuQF6QHFPGz/xoEewAA="
