---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr/
  - flaresolverr/
  - jellyfin/
  - prowlarr/
  - qbittorrent/
  - radarr/
  - recyclarr/
  - sonarr/
  - namespace.yml
  - middleware.yml
  - secrets-oidc.sops.yml
