apiVersion: v1
kind: Secret
metadata:
  name: secrets-mediabox-oidc
  namespace: mediabox
type: Opaque
stringData:
  pluginSecret: ENC[AES256_GCM,data:XeHyaIWr74oAF3fGoe3coFyOzgKwjDUasIELM1k/q7Q=,iv:uhhcc589jQvSxT0NkomSXZhNXzF4UNQI8OoKT76alis=,tag:nmMF8v+ACvVfaGwvd7mQQA==,type:str]
  clientId: ENC[AES256_GCM,data:N5FahZL0JKa8IwukK+N3rI8f4VLHXq8IJ5UPeDIFLVpRO684,iv:F0FEBztl73PwpLacWqJ7eCf9r6Q47lpPf5NM9qQWdso=,tag:iWn5kpRrQ/lmeDyMd3zwAQ==,type:str]
  clientSecret: ENC[AES256_GCM,data:vOeDn4rMxUb3zT8t2FKouqUW15UNs2d77qjG8YqjfCI=,iv:2ET0ZVrPS9jiz8PaR+3JEni4nR3btkFi7M/Hz/9yEoM=,tag:2LwXtupOoxEcQxAOSNSfsg==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMExzTjBsaDJFMlJmMmVs
        dkJLQk5hNEpzWDhlWjdKdHBPWGxqellyYVdnClU0YWg0Y2F6RmJRbGNvK0l4ZEFv
        MU1KaEZRWG1nUi94ZDhZTCsrbDdDaTAKLS0tIDk0MTRjdFVwMWdpVGN5NGV3V3Iw
        c0ZVVllWN3dicGxYTGRxQnllSzVIOFUKYQhtD0SUXSBgxX/tg7NU4Xat6f8qn1Mq
        GKpE7qQ12bhH4/emK0IOcRiXxUoVruJVTaI8l9Li1sBwX7strLN7nQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T03:18:17Z"
  mac: ENC[AES256_GCM,data:wxrFKTYe+CggzHBpSt/wjloo1v0dykhkwnedw4kyhptQ6WOSv2iPel2mBF8BHo0UiMFy+6g5yhog7MZL2Ih/RDm8mrv4vyKy8IXBS58aLNEyPtQW0zTLZFkmCkibjRPaNtQsAD2bDTFe72flsNCc4thXTPFCuuL4fKOTcPUxxiw=,iv:pHtXh8h8VEhsTZnuY2bAMQSYdL4Rgxorz2e0f57fNaI=,tag:FCMYDZognvL7+SKnvPiy9A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
