apiVersion: v1
kind: Secret
metadata:
  name: secrets-lxmd
  namespace: reticulum
type: Opaque
data:
  identity: ENC[AES256_GCM,data:gf7FhYfWMuYe+JZW1IYr2t/x3afg3a0JyLTioISlzLhQyqqvN3bDxEcHhnm2gw79BZU3G15Ko2r1L8ZEM2IwRQXzb7rsvwWZqqoTxWxQArWlwNgpDFrUEw==,iv:rvmfcCpEuDfPPB3AIoOAnnTLwPq+/hlEDufERWMFlYI=,tag:W3bKuXT8rayZJVNFqsaifQ==,type:str]
stringData:
  rns-config: ENC[AES256_GCM,data:03xV/LvcC6QnxSdmMFy47/JqGmV+Zsy2NdPWS5MtJU+4Y0Egsjd8RhX8fAJJtMtsy7FFDsDGhOnmvZPIOx/InM5tSNXEQ6gIGcAaCPJiUzqQobz1MyvxrgdCTmcvSZStFgCoGKH5EHengx6d1Ofe4xSaWqka0vWaZJ1xRSns35Zg3KuY9HtAWKl0CKglq/RcMgYTTiqdN91Iqw3KAU5Y9UUa4Lv0LhplU7GIAA3XDtyslRSJCn34KC3XGAoZFB5Vupj79NznAzKUbZu9r/+pHRXfT+IWduxMwtSLMkMuVDIAAKYNvm75SLZPUPRdfBc5iTXeu0dOxR6jv8P2cyd1okXVUAoBSKD6pQFxDSTKGhsW9OUw3A6OaFmP6VjPXUGMtMbcW/moX0WZwJraQ2w7QxYVCJjOXCOzdg==,iv:nE+OIXlqkipjJf5yVWH8Tel489pg8+BLo6WukqODHCk=,tag:+F+rgY/FDTiR2Oz2oOOiWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbWFxSWJiSXl0ZG1DazMy
        TEVsQldvUGRWNlM0WjJVZHFiOVdaUW0vdUJjCk1RSDFwN05tY3E0VDh3T0RaOUx3
        dys1YVlmTlNBNVh0Wk41QkdtUzZmUG8KLS0tIHZmWjczWVM5czVvNFhXb0pRemJX
        VjZoSTAyc1FtTGVBdjJQVHI4S3pCTG8KYLUVxFy8eJ71v2DHP7WUk+7f8A6PUQsr
        g12ubv4mKp20ak7TsU4xqdQZjOC1+tXeskgMfFRKeEJjBuT68qixQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T04:38:57Z"
  mac: ENC[AES256_GCM,data:tckkdMTltEMrnJpAK0YdqV/ySraIoFEE7g74nCDefCw/ovyPc4BBpgGcqKx+5tX9/yea0CmHYRtNDmuUTx3mHuVH4NV9Q9c1afAs/tLpMOZb+dFUENe7n0gLuuu9pM61KF201XGmvq0/V3ycemjPNi6Y6sJFvZbmxlYE/Y5ikIA=,iv:7LyK6tmdthu1mN6mVejxBi8RZf8sBGAyPXNEQ8ai8lY=,tag:oZVZ0MAxwrRcYLtLEGiDxw==,type:str]
  version: 3.13.3
