---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - secrets-openwebui.sops.yml
  - release.yml
  - ingressroute.yml
  - secrets-volsync.sops.yml
  - volsync.yml
