apiVersion: v1
kind: Secret
metadata:
  name: secrets-openwebui
  namespace: openwebui
type: Opaque
stringData:
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:P+/QHH7UJJ/w9kRTtk4LrSpHs9rJpFyFHUBrAF0LJ3sdFbjf,iv:fbj4qlj+jB9pyNxK5QF3l9Dphcia4iPjb9/8XL2kGzI=,tag:cYO+oGM/cUnkXI/n8aaQCw==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:XOouzAf3Sg8m8X0ioGHc4cPf4hWC3/bjudR8YpORXyU=,iv:4fNuQBaL4tWaDRLNE1BAUMUS+xL1l1X5cgv+b2quZ2Y=,tag:AM2hjiRmEbjMnMhhfo7Cyw==,type:str]
  OPENAI_API_KEYS: ENC[AES256_GCM,data:KyWzLbpg0QgdwURkgUVC6ck461oKx/4dokcVMyYTDGFMQM77zBkl2TrZfturlb45Ozw9kBrUJ45hGcdKC4QaaA==,iv:JsgABXtZJPQKJUcuQAfp0cRS6+BcdCehcQUSxdgyBG4=,tag:0D91VNkPHngogrLv3acJOg==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZG56N1lZYmxVUHNOOWkv
        RXhoVnk4d1hPdHNNVlZyS1lKVDdIcHN1VGlZCkVoMzFHLzdKcXJOUW5pMmZoNG5m
        M2d2eXZDRDRrWnNhcllwVXFLZnh2UlUKLS0tIDRCSEFtWWYzSEFDaE15eFQwb1hD
        OHNpWFZrWUpveTFzTUZiWjRMa2JpS2MKGeZ4X3mMiZl4WQAFCEsSWPrD8k4hLU3E
        6gwjw1D+Ub1dxxLIuiUTb+v4q3lIJhl4Ob7rGu9IIWznbvlBu9gEqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T02:39:19Z"
  mac: ENC[AES256_GCM,data:cGSze5z6yDx8OSNRkMEUzn8NAAeQOEiN0+P8tyqptStbnwvtQuHLl+JLlnKfcV1dB659sFCY5p+aqiJu5rJ1VfOrhIWYelZNZsrZ/nnogaBzR+0kCkPUq4AgfMpIMcin8AOPCXpE7aEb3Ka3X+2IKd1P6oty1qyio8NMHlBcAYY=,iv:4SQd8ktcUoIFA9qrqziPC8QzP9Wt+DuxNISfyR3rrT4=,tag:UZWuFJKlKF1C0OGEolTaTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
