---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-vaultwarden
  namespace: vaultwarden
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  imageName: ghcr.io/cloudnative-pg/postgresql:16.9
  bootstrap:
    initdb:
      database: vaultwarden
      owner: vaultwarden
  storage:
    storageClass: sunbeam-nfs-csi
    size: 4Gi
  walStorage:
    storageClass: sunbeam-nfs-csi
    size: 4Gi
