apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-configmap
  namespace: home-assistant
data:
  automations.yaml: |-
    - alias: Porch Lighting On
      trigger:
      - platform: sun
        event: sunset
        offset: '0'
      condition: []
      action:
      - type: turn_on
        device_id: 30daa89955e6b9ea139baab53291ed57
        entity_id: 30c93b3e08f3244d6486a83e49f15b3f
        domain: switch
      mode: single
    - alias: Porch Lighting Off
      trigger:
      - platform: sun
        event: sunrise
        offset: 0
      condition: []
      action:
      - type: turn_off
        device_id: 30daa89955e6b9ea139baab53291ed57
        entity_id: 30c93b3e08f3244d6486a83e49f15b3f
        domain: switch
      mode: single
  scripts.yaml: ""
  scenes.yaml: ""
  configuration.yaml: |-
    # Loads default set of integrations. Do not remove.
    default_config:

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16

    homeassistant:
      auth_providers:
      - type: homeassistant

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    recorder:
      purge_keep_days: 10
      db_url: !env_var HASS_POSTGRES_URL
