---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          home-assistant:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.12.5@sha256:638e519c874a06389ce6f03e435dd80a6697e8692eac88b459775839410f3439
            env:
              TZ: Etc/UTC
              HASS_POSTGRES_URL: "postgresql://home-assistant:$(HASS_POSTGRES_PASSWORD)@$(HASS_POSTGRES_HOST).home-assistant.svc.cluster.local:5432/$(HASS_POSTGRES_DB)"
              HASS_POSTGRES_HOST:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-home-assistant-app
                    key: host
              HASS_POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-home-assistant-app
                    key: password
              HASS_POSTGRES_DB:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-home-assistant-app
                    key: dbname
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 8123
            protocol: HTTP
    persistence:
      config:
        enabled: true
        storageClass: sunbeam-nfs-csi
        accessMode: "ReadWriteOnce"
        size: 32Gi
        globalMounts:
          - path: /config
      configmap:
        enabled: true
        type: configMap
        name: home-assistant-configmap
        globalMounts:
          - path: /config/configuration.yaml
            subPath: configuration.yaml
          - path: /config/automations.yaml
            subPath: automations.yaml
          - path: /config/scenes.yaml
            subPath: scenes.yaml
          - path: /config/scripts.yaml
            subPath: scripts.yaml
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
