---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          home-assistant:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2025.2.0@sha256:1191a95f9b82df94f467ad14dcb02bd6a5ddf244f8cf54a983c84a63bd612752
            env:
              TZ: Etc/UTC
              HASS_POSTGRES_URL: 
                valueFrom:
                  secretKeyRef:
                    name: cnpg-home-assistant-app
                    key: uri
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: [/bin/sh, -c, '/usr/bin/s6-svstat -o up /run/service/home-assistant | grep --quiet true']
                  failureThreshold: 6
              readiness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: [/bin/sh, -c, '/usr/bin/s6-svstat -o up /run/service/home-assistant | grep --quiet true']
              startup:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: [/bin/sh, -c, '/usr/bin/s6-svstat -o up /run/service/home-assistant | grep --quiet true']
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                add:
                  - CAP_NET_RAW
                  - CAP_NET_BIND_SERVICE
                  - DAC_OVERRIDE
                drop:
                  - ALL
            resources:
              requests:
                cpu: 20m
                memory: 700Mi
              limits:
                memory: 1Gi
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 8123
            protocol: HTTP
    persistence:
      config:
        enabled: true
        storageClass: sunbeam-nfs-csi
        accessMode: "ReadWriteOnce"
        size: 32Gi
        globalMounts:
          - path: /config
      configmap:
        enabled: true
        type: configMap
        name: home-assistant-configmap
        globalMounts:
          - path: /config/configuration.yaml
            subPath: configuration.yaml
          - path: /config/automations.yaml
            subPath: automations.yaml
          - path: /config/scenes.yaml
            subPath: scenes.yaml
          - path: /config/scripts.yaml
            subPath: scripts.yaml
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
