apiVersion: v1
kind: Secret
metadata:
  name: secrets-pocket-id
  namespace: pocket-id
type: Opaque
stringData:
  MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:nCEXANdQjrFLzszWJRhDiQjOSCjo6nm9+gqciybDXSHwAgl2p9eXTA==,iv:nlf3fzaCCNg6n3DvE0N+Z8n5shXwLDzpWlOp7mIBxJY=,tag:9PG+5qdJnExWgpDM2e8GJw==,type:str]
  ENCRYPTION_KEY: ENC[AES256_GCM,data:lgl0/tvdRfuO8c/VK3W74xR3yLiJ2Wb+fCp31OpLmOc2JkhlUoaJn8ua/v4=,iv:UN9tvSnPy42m7mBuALlzBtNSpEIqIRRUG2FfXMaZEEw=,tag:uFeZYnjyY4IWsHgVejE7fg==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBic21oNG9ENGhraVhlZ0l3
        aE05em9La2RsTjhOU3BNZDFwY1ViN1llR1drCkt0TWkzNlVhTUZWWHBxOWQwMkdS
        QWZzQjFyRkZ1NERRTjR0c2RVTzN2ZjAKLS0tIGd4WWd4d1pQVkNGbXk4Y1NUZUZz
        eFgvOUNyUXppemdnSlFieEN6RWl6UmMKPfIsrS9ZWEIxDN+eE2V8Zr3yh2Bnk92m
        d9oeC0O0HJKub1WjuLIqz/mHI7XLr3EcANA8obMAA+Bc2VL1Mz758w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-19T03:19:32Z"
  mac: ENC[AES256_GCM,data:cXz1CxtMb9Oq8RBWf94urzQQwOcAyXdOH0fXZDFeE9Hk56PeSo5ARbvU/XsGCP4YjFXiNsAK/Du+u9tu72S5suZbopUpalwlEdXeSeAo/Nln0wZ0nVYuOrtTpkswHAWjHx6pAU2XOAUvckRHMMzXpwl7O3+u+pO4pJc4f6eEzEc=,iv:t2EodZRboRC2C+CLq8ijKDKSDQtrsTA7ekk5y59Ltkk=,tag:SdYmXJ3uj8ro/stWR8BsiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
