---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      server:
        type: statefulset
        containers:
          server:
            image:
              repository: docker.io/louislam/uptime-kuma
              tag: 1.23.16
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 3001
                  initialDelaySeconds: 12
                  periodSeconds: 15
                  timeoutSeconds: 5
                  failureThreshold: 5
                  successThreshold: 1
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 12
                  timeoutSeconds: 5
                  failureThreshold: 4
                  successThreshold: 2
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 60
                  successThreshold: 1
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 500m
                memory: 256Mi
    service:
      server:
        controller: server
        ports:
          http:
            port: *port
    persistence:
      data:
        enabled: true
        storageClass: sunbeam-nfs-csi
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
        advancedMounts:
          server:
            server:
            - path: /app/data
