---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
  namespace: volsync
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    manageCRDs: true
    replicaCount: 2
    metrics:
      disableAuth: true
