---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-unifi
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.15.2
  interval: 60m
  values:
    fullnameOverride: *app
    logLevel: debug
    interval: 2m
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: &secret external-dns-unifi
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/kashalls/external-dns-unifi-webhook
          tag: v0.4.2@sha256:c8eb92acd71170347b77096cbda0708fd573b55334274cbbc577dee051c7abd7
        env:
          - name: UNIFI_HOST
            valueFrom:
              secretKeyRef:
                name: *secret
                key: UNIFI_HOST
          - name: UNIFI_USER
            valueFrom:
              secretKeyRef:
                name: *secret
                key: UNIFI_USER
          - name: UNIFI_PASS
            valueFrom:
              secretKeyRef:
                name: *secret
                key: UNIFI_PASS
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    extraArgs:
      - --annotation-filter=kubernetes.io/ingress.class in (internal)
      - --ignore-ingress-tls-spec
      - --traefik-disable-legacy
    policy: sync
    sources:
      - service
      - ingress
      - traefik-proxy
    domainFilters:
      - layertwo.dev
      - layertwo.lan
