---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: authentik
      version: 2024.6.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  values:
    authentik:
      redis:
        host: "authentik-redis.authentik.svc.cluster.local"
    server:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_SECRET_KEY
              name: secrets-authentik
        - name: AUTHENTIK_BOOTSTRAP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_BOOTSTRAP_PASSWORD
              name: secrets-authentik
        - name: AUTHENTIK_BOOTSTRAP_TOKEN
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_BOOTSTRAP_TOKEN
              name: secrets-authentik
        - name: AUTHENTIK_BOOTSTRAP_EMAIL
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_BOOTSTRAP_EMAIL
              name: secrets-authentik
        - name: AUTHENTIK_POSTGRESQL__HOST
          valueFrom:
            secretKeyRef:
              name: cnpg-authentik-app
              key: host
        - name: AUTHENTIK_POSTGRESQL__NAME
          valueFrom:
            secretKeyRef:
              name: cnpg-authentik-app
              key: dbname
        - name: AUTHENTIK_POSTGRESQL__USER
          valueFrom:
            secretKeyRef:
              name: cnpg-authentik-app
              key: user
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: cnpg-authentik-app
              key: password
        - name: AUTHENTIK_REDIS__PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-authentik-redis
              key: AUTHENTIK_REDIS_PASSWORD
    worker:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_SECRET_KEY
              name: secrets-authentik
        - name: AUTHENTIK_BOOTSTRAP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_BOOTSTRAP_PASSWORD
              name: secrets-authentik
        - name: AUTHENTIK_BOOTSTRAP_TOKEN
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_BOOTSTRAP_TOKEN
              name: secrets-authentik
        - name: AUTHENTIK_BOOTSTRAP_EMAIL
          valueFrom:
            secretKeyRef:
              key: AUTHENTIK_BOOTSTRAP_EMAIL
              name: secrets-authentik
        - name: AUTHENTIK_POSTGRESQL__HOST
          valueFrom:
            secretKeyRef:
              name: cnpg-authentik-app
              key: host
        - name: AUTHENTIK_POSTGRESQL__NAME
          valueFrom:
            secretKeyRef:
              name: cnpg-authentik-app
              key: dbname
        - name: AUTHENTIK_POSTGRESQL__USER
          valueFrom:
            secretKeyRef:
              name: cnpg-authentik-app
              key: user
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: cnpg-authentik-app
              key: password
        - name: AUTHENTIK_REDIS__PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-authentik-redis
              key: AUTHENTIK_REDIS_PASSWORD
    redis:
      enabled: false
    postgresql:
      enabled: false
