---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-upgrade
resources:
  - plan.yml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: node-profiles
    files:
      - kirocrew-userns
      - kirocrew-seccomp.json
