---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        annotations:
          secret.reloader.stakater.com/reload: secrets-vaultwarden
        containers:
          vaultwarden:
            image:
              repository: ghcr.io/dani-garcia/vaultwarden
              tag: 1.34.3-alpine
            env:
              TZ: "Etc/UTC"
              WEBSOCKET_ENABLED: "true"
              DOMAIN: "https://vault.layertwo.dev"
              SIGNUPS_ALLOWED: "false"
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-vaultwarden-app
                    key: uri
              ADMIN_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: secrets-vaultwarden
                    key: ADMIN_TOKEN
              REDIS_HOST: "vaultwarden-redis.vaultwarden.svc.cluster.local"
              REDIS_PORT: "6379"
              REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: secrets-vaultwarden-redis
                    key: VAULTWARDEN_REDIS_PASSWORD
              DATA_FOLDER: "/data"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 80
            targetPort: 80
            protocol: HTTP
          websocket:
            enabled: true
            port: 3012
            targetPort: 3012
            protocol: HTTP
    persistence:
      data:
        enabled: true
        storageClass: sunbeam-nfs-csi
        accessMode: "ReadWriteOnce"
        size: 8Gi
        globalMounts:
          - path: /data
