apiVersion: v1
kind: Secret
metadata:
  name: secrets-vaultwarden
  namespace: vaultwarden
type: Opaque
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:Zh4i4GfAf/60zOK9aJKHk1/g8CGxlIm1B8WHbpQ2mYnGrFjCaTw5Qg==,iv:XtoTcl3Xg/eRNRCWGK18GAwjU5dpyjVaPU9YJYOXd/o=,tag:Kb9iC1ONZYuQrl3mgKp1RQ==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArc0ozaUlxVmZrc0xvVHhV
        cW1JYjVWMS9xdmF4UGgzdW5Odm96d1MraUJVCkNGbnBlSHA5bTd5V3VzVzNuSWha
        OW41M2ZZOG5TS3lTaHdnSDlZQ002VFUKLS0tIFRPaFJkdVBmTG94QVVxbEliWGFP
        UExrUEZPaGVpbStoRW1QUWRYWjJxT0UKc+Phogp8GPby6X5Yk/pz+Mdx0o5iHMgi
        7zkU+RhSxffwM8B9PH7hTMHe3kdCcvFaOVqHJ+fP1A8192dM8LIX1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-19T03:00:02Z"
  mac: ENC[AES256_GCM,data:j8/xKpzncw3y3cJwyjq4PcTIjTQ42m09SWAhIpg1FQY1P5elfMrsZT+hUb0M1vTNt2f2U8ysV0wHk3TI0TbmNkOvXteI2Dc5JZOEPOgb5fdO5P0+PktW+GQ6yTdfcgSKvAjj2iOEOrzWT6zaYhUfRF01hcpLuJCrTMYuatiH/Hk=,iv:0hSsYnQCoUknzffNyf64Jjs0r0xzTXChZe/b5L68/OA=,tag:gXFCPbk/12DsgfOvkZRMZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
