apiVersion: v1
kind: Secret
metadata:
  name: secrets-send-redis
  namespace: send
type: Opaque
stringData:
  REDIS_PASSWORD: ENC[AES256_GCM,data:3ek/CTjsJ7iuLJvR6aKF2i1RmLSzlCATrxj/Iirn1Q4Fwr4nC7FgM9Wdy6GWPELs,iv:aH5oOePXrilFqxXf9hrk2LNeJpt0gjNuyO83VQUZbAc=,tag:/qiZ2X1mSAMy2joF4lontw==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQV2dhakFSekdZdXNPdzN6
        V0Jpa0dFUWRuT21lRUtiQm1WN1o1QWx3RVE0CmxyL08wM0s3Ly9rYzhFMFBZSW9m
        SnljWHJpMVI0M3ZHRjRvSVFScEpaR1UKLS0tIEZwSWxMS0tTZ0hCNXAwVEtKeFp4
        elBpdTA2RncxRFJuYStwTHE5R3lUNjAK9X+XfEqcXNgPFV6ofnY6U9F/En6QoRAo
        k4N4W1EQjWVyussTJkmvV7bzYV5IlYyMFnOEz55lsNfKKJub9tCAkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-29T03:13:07Z"
  mac: ENC[AES256_GCM,data:emeqVXAvHPb08+/Xy/95jGIIROpSEwmfgI16f75wI183NLeNIkxXaJiZ6eLvgQ2JqC/O0h2VLF1ljPJmrjVaPvv2Hm7MU3FwENSHgmERFfDuBRm+BygKbs8BOQhonpQxcU1hDd1Ox03d/gDytxi+NX11z1S6DpSeh35RZrH5O5w=,iv:6EX+uZ9Xhgg3F4ClS4eDjoT3k2BJm4yz1uH+WFSh2us=,tag:J520wLNVedHq/TCFmoWLHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
