apiVersion: v1
kind: Secret
metadata:
  name: secrets-send-redis
  namespace: send
type: Opaque
stringData:
  SEND_REDIS_PASSWORD: ENC[AES256_GCM,data:MBHQ5NWZCTVelm4OS4yeBYraYe84cm9ksYcKCa6qilTCtdYuDHKA/w==,iv:hwXlghJY+mUmAr0aIvgVt3I0Elj+Sgwg5ACuUJZZMvo=,tag:GlJHI/mI0ilf8P+BbXx4Mg==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TU1wdG9NRDZkZFUzaFFy
        NXZFbDA1azRYRFZVTDgyb1BPQ0U2MlpYQ25BCnlwdjdsWGpkZnJZR21VeFlJbHM0
        dWJmaW9KZlEwZTRTWXRqQ21mTk5vZDQKLS0tIFA5YUlXQmdJZzRVNVlXS0JtNXR4
        WVNLLy9BSi93YXo2c1lPTkc5TTNRVTgKq0XHKWDSe2o/pzbW77yQPgAl9WyCYVAE
        D0Ktn1QE+Uz7iyvK52hVdDm2PmKcCSBYzSrRl/QPsLLuIvrIDIoeWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-20T05:28:36Z"
  mac: ENC[AES256_GCM,data:hQ/9fHtcYVQC5VkgwHrOUB9Q6NMXqypoSv0daxfWhfRjcmSFepfs55ISRBwotD6/NyM0TKp0pJ8xDQt7wLbZvs59KsDjOFPsjlZCejkOVOOyptP1V64fn5E9lzlbbhpIzlMmAZnVb6KkOf2VHLtDl951xEt5dIlzfoJpYeAuzgo=,iv:ojc+1tsI18nA+XJQNhULrAa79brEksoX4AXMLIEsM5M=,tag:a341p3cFtQpaC4kztELvpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
