---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      server:
        containers:
          server:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.122.2
            env: &env
              DB_HOSTNAME:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-immich-app
                    key: host
              DB_PORT: 5432
              DB_DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-immich-app
                    key: dbname
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-immich-superuser
                    key: username
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: cnpg-immich-superuser
                    key: password
              LOG_LEVEL: verbose
              NODE_ENV: production
              REDIS_HOSTNAME: immich-redis.immich.svc.cluster.local
              REDIS_PORT: 6379
              REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: secrets-immich-redis
                    key: REDIS_PASSWORD
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: &http 2283 
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup: 
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: *http
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 30
            resources:
              requests:
                cpu: 1500m
                memory: 2048M
      machine-learning:
        containers:
          machine-learning:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.122.3
            env:
              <<: *env
              TRANSFORMERS_CACHE: /cache
            probes:
              liveness: &mlProbes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &mlPort 3003
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *mlProbes
              startup:
                enabled: false
    service:
      server:
        nameOverride: server
        enabled: true
        type: ClusterIP
        controller: server
        ports:
          http:
            enabled: true
            primary: true
            port: *http
            protocol: HTTP
          metrics-api:
            enabled: true
            port: 8081
            protocol: HTTP
          metrics-ms:
            enabled: true
            port: 8082
            protocol: HTTP
      machine-learning:
        nameOverride: machine-learning
        enabled: true
        type: ClusterIP
        controller: machine-learning
        ports:
          http:
            enabled: true
            port: *mlPort
            protocol: HTTP
    persistence:
      library:
        enabled: true
        advancedMounts:
          server:
            server:
              - path: /usr/src/app/upload
        existingClaim: immich-data
      cache:
        enabled: true
        storageClass: sunbeam-nfs-csi
        accessMode: ReadWriteMany
        size: 10Gi
        advancedMounts:
          machine-learning:
            machine-learning:
              - path: /cache
