apiVersion: v1
kind: Secret
metadata:
  name: secrets-cloudtak
  namespace: tak
type: Opaque
stringData:
  SIGNING_SECRET: ENC[AES256_GCM,data:EoC49Wimepx5dnK3dPOYq4+WCtQetIA4g7vtCTHiYzodqXcLn63IvuWfV8PBVMLV3C0ma14iQvKDSXcgjy/ltA==,iv:ABhs8YAjghPZZyjk2o+BOoqdPzWsKwR1BQUiNcKUNMc=,tag:iBninW3W1e2IjBXYBPJd8w==,type:str]
  AWS_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:4M59ywkvOnKTh3IrpQnwts+bjVZ3X5C8jSc=,iv:YeFIwPgASXPYUt7WSS6pr2G/OI4C+UfQwN8FD+77HWM=,tag:DNg4UQ7WwfnskO8Hrv782Q==,type:str]
  AWS_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ym3qwWd8OxWQCh0Kd3Gw2wye22hFG+ZG1hzrcLbchU6xRnZncp5Cxz0Byz+nVii7WOO8OYyVbEQZbkZGBtNbIg==,iv:zFhn4vQWF5UEUeq4JHK8HSCmswj9RsnvToJyB6oqYB8=,tag:8EBAuAuWVOuAT37qEiYhSQ==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbzk1UGZBUmZ1WFpEUU45
        SFBmNUpEK2xvdXcrVzQ1b21PaEpKV3owMXlvCmRxS0ZvQUFDNjZWb29CM3U2ektH
        Q3pRRENDdDdoYVpkYk5Qc3BpK2htWlUKLS0tIGJKWlFPQW5PN3VFMWVaTzFQRmEr
        dU93dm5IQm1QK29HcVkxRS9sZnJIdW8KNghYbcev+H84f8khZ8pDmsHSd96gVnai
        aKBZT/++g7AipExwIJsVndsTjuzOUnPcsVgyejv7QNv09Kkfp203Nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T03:11:12Z"
  mac: ENC[AES256_GCM,data:QNX4OhG7k+UVTkT7juibkG0Z4VARW9k3C1OPyyi0DJSOP+iJNRDzbomnWvGY1C8iTosr0Ep9BLklCJa6BKhPIkVB/tw6+Qr2aEUjT25TmZl7DohJo7OIBe+GnKfHPIIlqTO5Ea80LxHYpnKw4TlyRY8Oc2iMHidleY/uHwhrOeg=,iv:a891cCujII28zQ5CY1yUkUq6QsqJAQqwR10fDeDkdNA=,tag:SSBDflNw8IXbaV+58Ah8vA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
