---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: ollama
      version: 1.7.0
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: flux-system
      interval: 5m
  values:
    ollama:
      models:
        pull:
          - deepseek-r1:1.5b
          - gemma:2b
          - llama3.2:1b
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 4
    persistentVolume:
      enabled: true
      accessModes:
        - ReadWriteMany
      size: 256Gi
      storageClass: "sunbeam-nfs-csi"
