apiVersion: v1
kind: Secret
metadata:
  name: secrets-hermes
  namespace: hermes
type: Opaque
stringData:
  OLLAMA_API_KEY: ENC[AES256_GCM,data:mzPv/e1COH8+y3za7iWyuqActtqpBg37UXJKWhDhO3ybGxLYIuGPcrCf1zydTdnpqVe+clkr43WL,iv:CTYLNLZzZenqqChcpJIeylup5wI7wUeBavHxatog2m4=,tag:88FqMcqp3n94IoMsOFK9uQ==,type:str]
  API_SERVER_KEY: ENC[AES256_GCM,data:VDOvjNLUBJTUZhX8/YLHLOLpVizEgb2EdiPaASJSGMB+MfpVyCIO2X7RLcWvguAPdCfvuvSZO9uw2Bp63LIsxw==,iv:AjdxkLilhJz1lQFsC3Sl35e/SLqedgG23eUlrm54zoo=,tag:WYJqnxO59fSgdlUUpNozyw==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArd1R6dDlyVzV5WUhQR3RJ
        SHM0WlJDU2l1NlZFT2NyMEJ1M3p4cVAydTM0CkI2M2lZRURYZlhhVWg2VzJiYWJl
        ZHk5K04yVjFNdGRHTTNRSVBvWXBORncKLS0tIEllVm00MWdhS1JaRzQ3SmZMS2gv
        VThpOHN1NmtvVk02NHRnV3JjQWlmdzAKl0iAqruYjQjk2o7RXiw2oAke7VbX4a2h
        D8DTyhFJehavFwCegcenKqJo7k/UPmRp2JAFzeqdvgO3JIoTufwhkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T02:38:41Z"
  mac: ENC[AES256_GCM,data:/EJzHjB+6OGRA72Mh2J5RwaiuItq/puFym5+pjkp1p72QP/lcTqR5A9+m7p60BOMEyyU0lrQaUDlFMQbm/8q9S1IZi7d8Qj4G/U/2m12xBNyiFZFwchWg5jF+pZI7yvfBtlA0aybsCmF16M13mWS1ZzAW0OCvgsSUPdPtOHM0U4=,iv:rbxc9TbA28BhQSxg6RiqgbDevlbU8a7+fOfJ0sX6yYg=,tag:lSGjiVcwiPas9VFfXGdzNQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
