apiVersion: v1
kind: Secret
metadata:
  name: secrets-hermes
  namespace: hermes
type: Opaque
stringData:
  OLLAMA_API_KEY: ENC[AES256_GCM,data:/FhvD0btA20ewsU4npGrM8gFBPb/cqcrSMntGKpwb+DCclfBhXjTcSCrqAqpdM60+WYfj2AUXKzz,iv:iL3tvbdzMv8lZbKCazjb9BA9ukB5HvU760iRXIEj+mc=,tag:x4U/+Qaw/hBAyjmhZ1pRHA==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2U2JoTDF4U0V4ajFQb0Z1
        NWR4L1hERHdhZW5obkZGL2RHSHlML2piendrClNIREF2S0FPYjI2TlNDODZnZUhj
        cmRrbXNpaHF2K1ZDK3F3UEZ3UE1sczAKLS0tIFgrZk9RK2NJMmdwOXVBdHV4VWZ2
        eTg0TnRWSEhJZGo2SC9HYWlEMlo5MHMKAp+qWBFag76ZPMwSyv/Co6R5C0ezoybX
        UGHIfEVImKQ2pfTTM2p2NEQt8xOJMPYNDdVNnpZRwbxxjDLozLZ9Og==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T00:38:43Z"
  mac: ENC[AES256_GCM,data:4Jz2Aza4qQpML5R8OX8UPzfpN6/n+zukRa9vhMV2AmX72djx1CRC8dO2ymSYDdSeQ3fIcX216iMQa847JKzaiXupON8q6E7Sq9nQ7SZlQX4pzKgH5m5Bpp05AUUSeASRc117dS0M45VcG36TmkFvQjws55L7UKNH8P3F9Zlh/H4=,iv:AC5uS7j/z6zCHDh1A0I9XrxX53Y9ncr3A/l9ZqQeRko=,tag:KPSFS4zwGtTDh9DDpuL6ig==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
