apiVersion: v1
kind: Secret
metadata:
  name: secrets-stoat-rabbitmq
  namespace: stoat
type: Opaque
stringData:
  RABBITMQ_USER: ENC[AES256_GCM,data:TurqTek=,iv:wL83QRZBhYmN06iYWyzIGV6kr+9OUFjaAk9dk7O7yXM=,tag:kwNeFOoQprwDPXa/KWTtdQ==,type:str]
  RABBITMQ_PASSWORD: ENC[AES256_GCM,data:i3uzeplpY4YtbVPNS0lADQPSD7yLu0Hk3N1ir3zpmM0=,iv:o8Al29vO8bQcliAIcgQ0orp5v+rqW8kKxk+LsmzR/RY=,tag:XQDzMDEnV+uLWhAkvwSOgA==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bjF2bSt4NndaMm92cUJL
        NGNRckdFdWpoQ3pWaThqTktYU1RreXRKcXcwCjFMSVI5aCtxd3FQaWpJSG9FeVky
        QmpxbXVqeWc4MTZwSmkyaGV1UkZwSk0KLS0tIG5jTnFSN29hVEpjS21FQlpyYzRr
        bEdnaE95ZmpGWnZuRUlLdEdxVkxUREkKxm4RDPTpgvrfj1oi6Ot2q5bSPt2XdWz2
        55KevQ3iGLh5FUEa1D09aCCNsOvWxeH6SR5kSBYcdAg+1+iOafHWjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T04:00:53Z"
  mac: ENC[AES256_GCM,data:h00lQyG0L7TBbUboRy54TpG6gEdGNpTcusHbR729owUA5gvpJjVbG9iaLI23prqhJFRXTcK/XN3QFE31Kat5bk7/xLr30ZnkpwB3MwnyLku910662IWN3sip2Pnd7VLHOrmgk9X5Mc6S0iMvMFppxzKUkgNWhVbMT+4/G2Y/5Uk=,iv:T86/4T9I6Kt4g3hKFpytDR6TjvCIJ0SLPmSe2eXjPLM=,tag:WDv5Q4Qt2h7BELGwTYY+6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
