---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: traefik-system
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          nodeSelector:
            location: home
          containers:
          - name: main
            imagePullPolicy: IfNotPresent
            securityContext:
              runAsNonRoot: false
              readOnlyRootFilesystem: true
              #capabilities:
                #drop:
                #  - ALL
              privileged: false
              allowPrivilegeEscalation: false
            env:
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    key: TOKEN
                    name: secrets-cloudflare-ddns
                    optional: false
              - name: ZONE_ID
                valueFrom:
                  secretKeyRef:
                    key: ZONE_ID
                    name: secrets-cloudflare-ddns
                    optional: false
              - name: DNS_NAME
                valueFrom:
                  secretKeyRef:
                    key: DNS_NAME
                    name: secrets-cloudflare-ddns
                    optional: false
              - name: ENABLE_PROXY
                value: "true"
            image: ghcr.io/layertwo/cloudflare-ddns:latest@sha256:82634d63e24fc2d6b2da624dcc6f9f51ffd11424e9764d174db7782a3be112f4
          restartPolicy: OnFailure
          dnsConfig:
            nameservers:
              - 1.1.1.1
