---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strela
  namespace: strela-system
spec:
  interval: 5m
  chart:
    spec:
      chart: strela
      version: 0.0.12-beta
      sourceRef:
        kind: HelmRepository
        name: strela
        namespace: flux-system
      interval: 15m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
