apiVersion: v1
kind: Secret
metadata:
  name: secrets-send-oidc
  namespace: send
type: Opaque
stringData:
  pluginSecret: ENC[AES256_GCM,data:29tKDLi4AN5Vbo8X/5MTP2IIJmm7p6gQxdXDAx0jlcU=,iv:2KST7NhDvNlnBhKC9OkotmBiQ/C2qnrBhixuICUsqCw=,tag:SbzHdtrQ+Yp7tk0KPkwBpQ==,type:str]
  clientId: ENC[AES256_GCM,data:moSF4lnbYwIbkKrEY1CbzpjaHCLfjFA5FoKftOVXxsFvuVAD,iv:Dgobxrr3bw8NfRX68T+irDW/EoURgor9/LLnuHMeoD8=,tag:+PMcY/PcloSnXuOJVizazQ==,type:str]
  clientSecret: ENC[AES256_GCM,data:Haep3z6hHZWL/7QMgjLr0lVM4uwyG1AbPacA+dK+1NY=,iv:DoiJHxFzPWmpDxdpvKb9oI+Ce9+B5fMRGQGyzuElVec=,tag:V1NkE4GN0R6k+/iMErCd6w==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzN2VENlRORzFnd1VjVnJG
        SmNvT2Q0aWxZeERONVhDYSs5aHdkMTd5Nms4ClNXbDBzZ3pHcGtKTEFTL0QwTTRr
        cURSdWlSU3lqeTA4YlcvUzZHUWYrb2sKLS0tIHZ3NHZuS0VPSDh1TGJNVTl5L0hZ
        Q1RaVkVyZVUyVFN2azBTSGJGUlk3bVUKB+y69GjRPFQKBGIdHRFAVHIkzavpq7/U
        MsYAGL41m5oUkmJoBee8NY0WEMKEkaAmT/dmBe/O0Oon5F1l4UT2Bg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T04:36:57Z"
  mac: ENC[AES256_GCM,data:2ixXKcpTJWL0rzCF/HIiy8r6luT16ssBIabL3LEkP1v1E7/IpRAtpKryrHfEd10pgxtvqEUeSSj0Rk5zDH+zIVTJ8zSBoLwMv/kzYsgBOrsQWpS8GI1bC3bmUB755LDrRTdkpWy+rBYjetrwLfz7nBWseOw+B5uiexX5CF2wrDM=,iv:bjpVbgdrt66HayAPO+sjch5FuOa0r7VDz7rBe8p8vOE=,tag:fqEYzRN2jtcALnD2Y7XBtw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
