apiVersion: v1
kind: Secret
metadata:
  name: secrets-send-s3
  namespace: send
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:80ADp+ynYZMjEakCrSUvWp7xK+oXeI1/GSI=,iv:OUtQlzd+II1FwCQ1KzNWzOvXkw9NqEKcSwMskVVXawU=,tag:6m7JL74I/UjOgZ88mT/BRQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vrnSjth+j4umTn7uU0Q6xK7KG3rCMCzEc2ce1GobUbEbBi4YleIUWf9/6nVQeQgJ6yY7sYUiDnykIFsn90Abbw==,iv:5ZSK48koqdl9p9b4wnTfAzRY9j0XIkMU2fThM7fzH1I=,tag:UssVL178renemMVk7NxrFA==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETldzVGVDY1k5ZlpjLzBy
        NjBKTnhOM1NaQ3o1ZmM1dnIzVlZFOHdVOWpZCnFKZGdsZTdZWjJSQWI3YXBxUDRw
        T3ZtQkxpR1pJR1FGbW80ODhnMjlyTTAKLS0tIFo5VTYrUzdVdnNHMDRLY0hnTW9G
        L3ZVOWFJNzQzbDVtNCt1MUE2RnBGM0EKF6nuppHi02IYJmBFkwzqSZVtm0SeeX9A
        ulsMa2AUVrtvQ8YaOib0H6gVdyKZJ3k42ejkm7Nsdc7gSa/PDpl47w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-29T02:35:07Z"
  mac: ENC[AES256_GCM,data:E5kP7uoE/pm7jQBrwy3eKqf5WrcTCG4UWqyxxKGMF3cZQYCpphNDMNOufZrr0IFQfEpnY1IhhY4LFoDwfYDn1krE4wxjRxlE8kDand08qMmy5JpGMvdMZox/dLT3wcOefBiOWRah8IvUW3ASs9SHUF9gf6j6P01kJOP93fpMWX4=,iv:xEHCCig16mpRmDDA0RjD8QNvKGXEPcLEsov43Jclbk4=,tag:Xe/34tYAIaTsEj4IWlS3FQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
