apiVersion: v1
kind: Secret
metadata:
  name: secrets-stoat-redis
  namespace: stoat
type: Opaque
stringData:
  REDIS_PASSWORD: ENC[AES256_GCM,data:XVXNKP7z4CrZWjMAbOvPv6IIEyk/cFNM8YAQWJAvVt0=,iv:Znm2uNOfxHxvxLaIC6bnhRXBnFUnN+SsmheFYIXWkpo=,tag:ic1gER81MotPKOqV3v+FHA==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveUlVZ0VoWWtKSWxUVDk4
        dEtZWUt0aVA5VjlUMC9LZ25taitya2VGcWl3CkQzN0ZZY2FDbTFGZ3ZmS29NeGdQ
        cmFDajFHU3VPaWxBT3dWUkpsclBsdTgKLS0tIG04UXpwOUdMbFlGOE56dHdHUURD
        TFRJVW1FV3EwZDFoeVVqQkdIbmN0N0EKM7JvK85uwfORw286Y/vt27vCg2lj7AOM
        5HqK9/34w27nZvTphzDJeXAPPuVnMoxrEMPkPxD5rfmdTCkIggzuEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T04:00:43Z"
  mac: ENC[AES256_GCM,data:lpVhHxciNYnt9rwzbeFAlpUEViUAuJtJchTcFA1dxPdzR8tAT6X3xyqtYMZNxLIzGGOBhBSdUyu0Ht5+BwEpa6eS9Jl4/mBWXEhntPnOMW948c9JhqxQMjwZ3Ea5KIZFjjiAdTX8c6SSQyKdjFfjNzXUBZIqMP4/BNEnIBNgJeA=,iv:3OQVfuCzCu9PZvdEVF42yIsu+lqlb2PamLtKihZG8+o=,tag:ULHFqo3LYHZOOxXb58Et9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
