---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: mediabox
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      recyclarr:
        type: cronjob
        cronjob:
          schedule: "@daily"
        containers:
          app:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 7.4.0
            args:
              - sync
            env:
              TZ: Etc/UTC
              COMPlus_EnableDiagnostics: 0
            envFrom:
              - secretRef:
                  name: recyclarr-secret
            resources:
              requests:
                cpu: 5m
                memory: 36M
              limits:
                memory: 128M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      dnsConfig:
        nameservers:
          - 1.1.1.1
        options:
          - { name: ndots, value: "1" }
    persistence:
      config:
        enabled: true
        storageClass: sunbeam-nfs-csi
        accessMode: "ReadWriteOnce"
        size: 1Gi
        advancedMounts:
          recyclarr:
            app:
              - path: /config
      config-file:
        type: configMap
        name: recyclarr-configmap
        globalMounts:
          - path: /config/recyclarr.yml
            subPath: recyclarr.yml
            readOnly: true
