---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-external
  namespace: traefik-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 33.2.1
  interval: 60m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    ports:
      web:
        port: 80
        transport:
          respondingTimeouts:
            readTimeout: 0s
        redirectTo:
          port: websecure
      websecure:
        port: 443
        tls:
          enabled: true
        transport:
          respondingTimeouts:
            readTimeout: 0s

    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-layertwo-dev-tls

    service:
      spec:
        externalTrafficPolicy: Local
      annotations:
        external-dns.alpha.kubernetes.io/enabled: "true"
        external-dns.alpha.kubernetes.io/hostname: "traefik-external.layertwo.dev"
        metallb.io/address-pool: external
        metallb.io/loadBalancerIPs: "172.31.0.30"

    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 4

    ingressClass:
      enabled: true
      isDefaultClass: false
      name: &ingressName external

    ingressRoute:
      dashboard:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: "traefik-external.layertwo.dev"
        entryPoints: ["websecure"]
        matchRule: Host(`traefik-external.layertwo.dev`)

    providers:

      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        ingressClass: *ingressName

      kubernetesIngress:
        enabled: true
        ingressClass: *ingressName
        publishedService:
          enabled: false

    logs:
      access:
        enabled: true

    globalArguments: []
