apiVersion: v1
kind: Secret
metadata:
  name: secrets-immich-volsync
  namespace: immich
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:IyPTYqzQl16qHCB73sjfApi6TKCVMTeaLqHbiXrtxjGX2hMdpW/sgm0LDLTcUVEPAQXbXiplLhduGy8wrDe98KlmrtzPCg7765hg6QJ6Csd8Ber+BPEXw4II77dTVW7E,iv:rd7w0euPQXor8Ln55k2Nysf4Yl7IPgb2LPFfo0dfbAw=,tag:9kfiGcx1KB/IBOv8CEhN6w==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:0y7iIiiS+h5X1de27HEd/+jWQiZiUJu28plFRCpqzxN0rT+zq7mJJR33nueqoWzRse5UgsHCHm0M45Z3dl5XLQ==,iv:M0uoZwvQ4B0fjCNIZJY73zYA1oNZoJ5YpvRfhkbHLRA=,tag:A139pkS/39LYjqPT2H8jnQ==,type:str]
  RESTIC_COMPRESSION: ENC[AES256_GCM,data:nx8Y,iv:p4uOKJg0cPtfohG7dLALaUt6XApf2ZMVYtSYO0IDi74=,tag:LDjM/t2KRmkKccFe65X1Lg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7gMsNU9dRh10JPcri+pfOkCdl2g7tpYCYIZJyFuD5CA=,iv:9FI9N+69SzSxKx4GghJhpVXxTCk2E6/SC2FebEJXyio=,tag:AKWeFElg1qkZ83Whu8hMMQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hGxeWmGcrnNEpcP1ipdydAWx26L34qG7ZTQ8hVJ3Bh4h9Imvis+j7PZwJT9axTc5UUgNAqGmrL4++PkSX8qojA==,iv:HwZ6zr+7fwB/tmoHyyaiUyFrgpOIXdhjgk4cjGk5r3s=,tag:vgDQ56vS4TrX8vGNS1YSrA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZFhCVURDeEl1QWlORHFC
        QVJFd29hY04yQUJCR2lZWDBGSURLMHZRN1NjCkY5YWFWY05nZmpjY090VEp2UGZI
        dm1NeTdWWUtXOXZPbWxQaWVtUjZCa3MKLS0tIEtuL0duMnY2QzBqT1JtRkM4M2FG
        TVoraTNTVDYvYjY4dkpkemFCbUp2STQKTbntZbC5ophK+ImlIhpxttqhPa7kAFZm
        HT4M9TkoCcPT6mCHtxZaOScTL5qOWQonPDMLdF4G2MObtXn9c4Osuw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-23T16:36:21Z"
  mac: ENC[AES256_GCM,data:5SBjRsPisbH1dHe/30gnIEKSvq3ztHbXYm1TGW11cpwGa+4I6gS7Qnjn8170p0kgBwsbHz/S4DV2KIaoHuUgssxUtKFkmKl1vAlKy/eViaKFSPIghbSIlR3kz2IleBjiU0MteivxwknQo4AzNJ4031ZyLAdO1pxdkJzxb1RfJus=,iv:k7TCjFMv4CPY8xduIt9TApyXyZ1764FjGFcHeTeRQG4=,tag:6wfqBsFMLHjASZl0wgmDAQ==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.9.2
