apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
   name: immich-backup
   namespace: immich
spec:
   sourcePVC: immich-data
   trigger:
      schedule: "0 */2 * * *"
   restic:
     pruneIntervalDays: 7
     repository: secrets-immich-volsync
     retain:
       hourly: 1
       daily: 1
       weekly: 1
       monthly: 1
       yearly: 1
     storageClassName: "sunbeam-nfs-csi"
     cacheCapacity: 10Gi
     copyMethod: Direct
     moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
