---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: forgejo-backup
  namespace: forgejo
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: cnpg-forgejo
