---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets-nextcloud-admin.sops.yml
  - secrets-nextcloud-oidc.sops.yml
  - secrets-nextcloud-s3.sops.yml
  - release.yml
  - ingressroute.yml
