apiVersion: v1
kind: Secret
metadata:
  name: secrets-nextcloud-oidc
  namespace: nextcloud
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:m+DebKPnBDVGAyr+Jr9qRMvF44+BOOgjJlF9iIWaHd/2ftqN,iv:TVsHs1h5HwtYz5xDttjlH8BbTc7jq5L3ZOXjhSsxlH0=,tag:7h+Gg2nEix6kf74SjZ7qVw==,type:str]
  client-secret: ENC[AES256_GCM,data:TxHfjAPLBMiKl8vGDX2Usu9+Mj4Gg9cgkLTAczuh1lA=,iv:eInBMn3nMZLLFBzC1qGoml03rPGJuLHaEvT/WxJ4rGc=,tag:YnT2+rTG9mMNJiukLAcoKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQzd4UU1XWWZ1RjhYY0xD
        YURNK1JEYVVreUJDaUxaY3dialdTRE9hZkhRCllHenRkT1owWVRIbnYxMndsNXNq
        ZnNtbHlGbDFiL3ZxckVwOUFsR2VzdzgKLS0tIGF6Zk5idWFlUitSbkZ5U0c1eWNi
        V1F2cHVQTUxxakp5VmRwVjVJbU14aUEK2mhvBDR4CxJThZ9evsUheaIvez3YyjrD
        0sxC9D8uWGRBg55DdwKwjV8GMebsfQF+bZGTH7Ua7qqMhlLwhESQ2g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T04:37:31Z"
  mac: ENC[AES256_GCM,data:iBWr5CJb6JPXrXOxBYrM/HVcB4ezUrL4q7wyeIHiBESY5Li4t0jh711ftVByVUm9+3xnvR7zFE0P+oIwXQl89B6WF2ynyFjomnydz8NL5R6CEjC6XGht3hVfnB2x6kRIk6F9+o1J0KvT43rGWBNK3tf9SBFh4oQb4v5yfs9a2J0=,iv:HaK0WrcULi2szB98WtuT58UxpkBKWvKr5q9UiZq8aBY=,tag:lIdSzlcncP9094msyFjMeA==,type:str]
  version: 3.13.3
