apiVersion: v1
kind: Secret
metadata:
  name: secrets-nextcloud-admin
  namespace: nextcloud
type: Opaque
stringData:
  nextcloud-username: ENC[AES256_GCM,data:Pdd9Qx8=,iv:C6JqC+JkNl8OnQvalmbZt+CdryI4fbD3rNMY2r3+atc=,tag:XWG7wjiEyirZrz3vzJH0QQ==,type:str]
  nextcloud-password: ENC[AES256_GCM,data:nRqA3Bnapix8sUJCY0Q/34A+cwKH5ifSNWbDQUT7iZWCqtrVMQhDywdnzUr1jeMZjz1WyTXKf1XnU1BSMNoxiA==,iv:rVghQqqYn3myK44pIbdP8Vx0b5WwV+h/JXA0GUPWgQM=,tag:f4bJNHZ6kp3IeuyYAunujQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWkQwNzF1NXNtSGMwa2I0
        d3FUSkI0OHRtOWJ3VEk3SlpaTTRtZ1YzcEdvClhKL2ZQbFU2R25RUmpxMm1CVG1E
        Vm9iVG5DUk9BT09VSFhNOU9pZ1RUcGMKLS0tIDFCeVY1SXdvaGZoUmNLcitHU3o0
        b0cxN2NOMnpSd3JEeXhjcW5IVFEwZzAKukq7jXVutI0AoDQFgQcqVTx6pSmAAbyc
        SReqKFEr3oyKPPdqWzJGi+IuZoE4nXm9xXCbKNzNoV71Pebqcuu3hA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T04:38:25Z"
  mac: ENC[AES256_GCM,data:/Su2zwCED842Cf5rcXZ3p+OyXEvAPMygFFIcMDGTqk/fBo+ckJFhywMsgQBaq8cDtqSnnen9kc+8Mj1WT+YLmIe8aGC7vs1n1pHmYW07FDJtrcaK2aglA1TMc6dRyUxPO9H8+Iviz4nkigNpMk+Xrtdc8ksrGm1FeYnBXi9UeL8=,iv:11ViZvWuqhs8MjuI1+aDys8HBbKse1jU6R2WklXStBY=,tag:FeJ1l9gHxjwE/S0+eEfRaQ==,type:str]
  version: 3.13.3
