apiVersion: v1
kind: Secret
metadata:
  name: secrets-nextcloud-s3
  namespace: nextcloud
type: Opaque
stringData:
  S3_ACCESS_KEY: ENC[AES256_GCM,data:hFzR8ukDxfs5wiVecda2h1hsHxNZlK7mdG4=,iv:85IH0G4/83Gtleqxzm4ffEhGWTFg9D11OetJqULAYxI=,tag:Sw5Rc3tHP5p/ei9qtXIz1A==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:qhhOBDMYBFOiCSKdmXsvhL4V7q4fnLVRyy5RSQmz9h3AfPx2QasiIIZdbH29wP6OaeVOV3FzkJE8lkjp588OUQ==,iv:uknpJez71MvU1H/75d3QVS2d4R62LmKcQIMy8BRJ8BU=,tag:pYLHkSPkRqsZr2z0nbM3ag==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQXFqTlVkaGd4emRIMU5I
        bnZtd25tNi9VRWVaR09QaDBTUnErdFp1MEVjClo1R21SVnRDVDdqQjRKUGsydHkr
        T3ZmR3JPajgrdm1rMjF1dUVzaWtzWlEKLS0tIDVNdk5CckM3L1FtZkpuNnZoQkRE
        djRXYk9TTEJ5QW5TSndaSUVCN3ZKUkEKtHuK9C4ZRleuCEroisNcNVCTGejxlyhE
        1N+vZQa+WoPw0rCDaefS09mvlL8o9tQArsfFZ6GLJbM9I8/626lZbg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T04:27:21Z"
  mac: ENC[AES256_GCM,data:Kc6SzZDAbQvyHVogJbJ1fKPjrPVt1eb5Jy7c3CacqujUskxQj0nPOl4AyBBzgabpwhPxfGHFDTeZuHY5U4g+PNy+T0vvq5e/s/SCxG+IKdV4B9sxYIml9vGdhP5y8bVCknWaqyYtOoBO47Ks6QmOuxLB5U+yvzfyuYFf704oM0Y=,iv:cly+/GYhN/5FEcSasS6OdHCEj3njRYqMAu/jXkEouxs=,tag:gPXXS5xX2x5s2pl2U3OvrQ==,type:str]
  version: 3.13.3
