apiVersion: v1
kind: Secret
metadata:
  name: secrets-vaultwarden-redis
  namespace: vaultwarden
type: Opaque
stringData:
  VAULTWARDEN_REDIS_PASSWORD: ENC[AES256_GCM,data:F9EoMv2aJw5hOTmJdx7ti3a+Cy3HcCDyzCcOcror9P3wFK2EefPopg==,iv:B2neGHaCnarfdzf8qRjL8zlZtFWTOWS83FYx1MYF56U=,tag:YpePQts3InqdX7iGro8Jnw==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYWtXMVZiL3BWa25ncG1K
        ekpMa0szSE1RNkN4VHk1VW8rRTAyeDlvSUN3Cm1OZUgvYVg1T3JRWEx2cWFvOVpP
        OVBMRGlGUTgvY2VvTEJYY3dlLzlQa2sKLS0tIDRkZEZrWVQ2Q3Z1SGxtR01WYjYr
        aTNGeGNSREkreVZWRTVtZm4xUjVCMGsKBnP3mBosEyzmM/CmZHj1pZF5YEntc0J7
        YPUi9JpnCQqu7QgGY0bapVJEnjimJlv4+3uIzA6F+preFoRHq8nFxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-19T03:00:15Z"
  mac: ENC[AES256_GCM,data:6QpSpnpiyOK3p1qNEM9VYjuWcV12OOMmMkBev2czziGMSQIpb53G7DB+WRXZ7RzJwxydghpnKt6OmRf7KbhdXgNZRFzwZzOEh1OtKe73+i4enJuOGSs+/QighvMgV2NTtSkMC2M4G1zp4RQv+8YMfXGRXcWS4bIrFvfiMj2h/I0=,iv:AxLUQjs8iZrttD5BY2BgVDpelXF721MuQ1lvvq2h0fs=,tag:XhL9kPmkjjJZ01SGpO6QJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
