apiVersion: v1
kind: Secret
metadata:
  name: secrets-rabbitmq-app
  namespace: tak
type: Opaque
stringData:
  RABBITMQ_USERNAME: ENC[AES256_GCM,data:L+u4++Pmt1wSIQ==,iv:tw+wvHYRjWfHSCO35u5DttjGfKC9lOh3JITbhHrw/5k=,tag:ZYGZB+3q7/TaVxRDwPUV/w==,type:str]
  RABBITMQ_PASSWORD: ENC[AES256_GCM,data:7PjruNMvYncCL+1GLbAl7F0wTAz7kI7Fsz3mTq7x8pgkufP0wcHDZ/FgbQ==,iv:N3Lqj8WkuRDzQaAbVOacICE0vhUvS0Sz8bbmZBoVZtc=,tag:p4qnS7zZOELA8Vxfm87s8w==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SkJyb1BuZlpIMW9RVXRj
        U3FYKzRGV09UNVhEcXAvSkFpRjA0cEtHaHdjCit1emlZQXkybi80NlRETmI1R3Jw
        cW5Jb3BtbHRwbElFZmwwMksvUEp6bHMKLS0tIGJQSmVRaE9uaGx4SXN6anlsWnRI
        YUFQWVJUNkhOVm1RdXN2a3pJdUU1Y3MKz0M+ORwutnHTrDHK/JehPL2r/x9eeZDL
        AN7XMLJVLO0sDg5RNy7i8Do4mnD1Dc7YOB84J//lX+zfepb+1OCQgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T03:56:41Z"
  mac: ENC[AES256_GCM,data:RncQN4hqUjN5NQOpKYoPs/9e/2sjRAu+8w+OC9mCC2JyS5o0juUspN0FhnTXzbHeNhGNJm1gIAH+DM5NwF6KRy3XW1dmXvyyIHXEK5aLggyiTtH7MfKZVBhEe2pVDPgQZZE6VkBUF38jddY7+ycf2lKyXgwb+9JxdYuJ9QVsq9M=,iv:oq1DNkGafHefzDdxN3nKZxR47MtLdPe5IaQfTMSGHkA=,tag:rY0LsTFBCrkiPSm0A6cDWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
