---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: outline-backup
  namespace: outline
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: cnpg-outline
