apiVersion: v1
kind: Secret
metadata:
  name: secrets-smtp
  namespace: pocket-id
type: Opaque
stringData:
  SMTP_HOST: ENC[AES256_GCM,data:AAt40KiAOo3P8w7EmbQNn6bLZg==,iv:sBDZf6wK++qYgLPgkgpPlBcAhmeLxiSL5+yqU2p6AG4=,tag:BqGl9wZ9Z2jU/KmN9v0nHQ==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:IzyDvP0++jugp8e+xMM9tCWnOB2gbTFeIg==,iv:Nb7ZVUZEioSTF3LfOgh4meqNJyFFWG+oiJeAIkfZcoY=,tag:1GmolTEka+LuclhB87Qrbw==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:SjXRIQt20DhOTFZuwHmHHijTAr7rRG906xiVvsVs,iv:JlpIWRQgu9EEzMYoLokVwCUq7y6p7x7/OfVSdt2nVxI=,tag:VCK8OyhhXgfbkONeojgPQA==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eXZqNTZYbk1hbGliREZu
        b1NwU3ZXUFBRMHdBdWI3ZFpONTJTUUhyaEZrCjU0RGNQWnpvTS9LaUlSN2d5eFl6
        c08yVUtYblNQaHcxM3paUGUyZThsYjAKLS0tIEZmd0UybVJ5UHd1dHhpbUJFa1hM
        TjArd0U2VGVVVzUwNjhuU2ZJTGdicVEKavuEneo6uy/hVHxt+8TAxSE2RqFxd5L0
        ikjqS98QkGixsL7I5U9a5NiW62W3N32bcYhCnxNlRnYwhCr8AamURw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T05:14:18Z"
  mac: ENC[AES256_GCM,data:VAU/ziR1h7Ea+uR0Nm0ov0e0U9gbe+9+iATYRMjXOJR7PCF6xfD6QZYtGlQFKb0JquLsNupHZROopw8FzpNEHdvFqMLj7aq/Ri0CbZaWEnB9qek3ZS/u3rFUkWPr1YCVlYEmEJJCgfr4Jdc0339XzIspS9JkG70EvynU1g/XuYY=,iv:XP6ED+HVaDz8lsZPVC/umbRUTCI69dQjc/ZUcN81wIw=,tag:BRssP3EjBD+YS2g2jA2+aQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
