---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hpe-csi-crds
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/hpe-storage/co-deployments.git
  ref:
    tag: v3.0.0
  ignore: |
    # exclude all
    /*
    # path to crds
    !/helm/charts/hpe-csi-driver/crds/
