---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ocis
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/owncloud/ocis-charts.git
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !/charts/