apiVersion: v1
kind: Secret
metadata:
  name: secrets-forgejo-mailer
  namespace: forgejo
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:vJnbBH+r37tsyfr7jWPQi7n7CRvV,iv:fk0vrgqWHtHsIY+HF+D70rjAzpXHnh1i5kXrQ0EhFkU=,tag:BXzVDNbuD/nT+tqC/2KPZg==,type:str]
  password: ENC[AES256_GCM,data:RJmM8Xh4bZ3zr5VlXQk/M+yktkcoHffMzWYqs974,iv:7k0Yf1rlvnfviohpIHNhmTbPE+iylvELIu46snh/vX0=,tag:iey4wqTwob8x/MDJCpCRmg==,type:str]
  host: ENC[AES256_GCM,data:44mz2MQj5svveoFT2stmsoPxSQ==,iv:ODJuwWttOfMGCnbXz335oLDWMH3FvwNVahplWyHAEzE=,tag:uZ1NRuUL5QwoTsbPQ/d10A==,type:str]
  port: ENC[AES256_GCM,data:PXEU,iv:xjLLfTlyeHSAd0WldNydIL8XSaG/P4Sg2mEY+tXvMEo=,tag:RCOaAMiEPM3kcC8N0HOgBg==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dUZyYTdvUVZkL2I1dmZK
        RCtvYi90U2tuTDNVbk5sc21lNDZZR2xqakhVCkNyZkFXczlmZzY5anZGVUJsNy9S
        M1ZweStZOHoxWiswdmtMdmNrbVF0RlUKLS0tIGJ0ajFpeW9pbjF6YkNKUEs4cTAr
        d3QwWEtFd3BZQ2dsSzJhdHZCTFFLN2MK6nPKb0KOly2m24ITDcxZ0ZEM5lr5IqLh
        5OIc6s2VMSBSaTbj2bzQ1tlm5DdivpFct8D6phLNQYzej54A5E7t6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T04:38:17Z"
  mac: ENC[AES256_GCM,data:QWZAukYT/FUTKt9hkdmo6icxFMFfnlW+B2FmN+AcEXnMSo8soQQmdsy/xxjqNzBWcxgkCG5Wkrl2B7dgxBymlzZHJFoH3PVtSymXu9d8/yzXoQgELcDQBuPIlWOZLkx1yKDT/JwwfEUH4JM2DBn1+u17wnvmR5S/2ALQaP/3YfY=,iv:ppXfVTAqSKaHK3I4JdNbHb3LWiU+uE7xesLOhcS21to=,tag:gj4Qia1QSFZm1KgPz7QgMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
