apiVersion: v1
kind: Secret
metadata:
  name: secrets-forgejo-admin
  namespace: forgejo
type: Opaque
stringData:
  email: ENC[AES256_GCM,data:O6K8k2sW/j0CUF0wb+aDCEjf,iv:cPBnRlsO8FTBCAnsiE/tIO6Gl+NBsO3x9n5RMc9gAj8=,tag:zpIAXEaRQfztAVaZFzLSqw==,type:str]
  password: ENC[AES256_GCM,data:IMIRULRa4qL6Si1lMLEdK8kmvaEL6r3U1Aoh+iuHKe8mwRLFh2lw9XnrcpNFSoeh1zqpe5Q1SvlrWukCJOZjsA==,iv:9vBvSB9GZECz1ShksU/X/UN1cgnO9uephzcY/PK2UZY=,tag:xfuGDMwg2jH5phcZy9Js1A==,type:str]
  username: ENC[AES256_GCM,data:h1TobMFBzAz9PKH05g==,iv:3J3ExowZIImQFVheMxZiS08pLBBOPBeea9/HgqlWeAs=,tag:sPRuh8YuU3DmbDiKm0mUVA==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTWlXdWpkcnU2L1IrN1U2
        T20vNlVoUTIxM2p1VlNTRnZ1c3MvYWw3VVRjCjhnMDlKeS9QRkhzZENoR3BLSXZL
        RHhySzA2TlpJT1YyTW4yOW1BaUUyRFUKLS0tIFJkNlZFWUhyRU9sWmQzUW5FUms1
        Y3BmTmdsNzl0eUV4K05DdnhmY1ZIWGMKc+e4OkH7VBzdYOtIskXA+U43yTXu61J8
        hrkWKDcIC0C81sgx8bLNZM5S9Pfb0MKpj4BSqaSR2PLB25Es3f+SeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-29T05:29:44Z"
  mac: ENC[AES256_GCM,data:LVpcJL7B80YGMCTT8Bou7u6F68Eg7lTEym3lUobYu+H05L6CaI2tVJvGK346sBNKI03FUHHJbJWN6NyUBueY9ihHzjj6YAU42VZszAq7twjBg7v3RIrW8xyRnXy4zTUOvGPZfhqcYwr7ew2W+tjDIHWfPN8g9OMJm/PsefzhNcs=,iv:nyXW7SJX029ho+Xs4rf52LtbTzpCkODQGhPDvbcXRaM=,tag:qx8omBpKJLOMi2Cp+qmvLA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
