apiVersion: v1
kind: Secret
metadata:
  name: secrets-forgejo-signing
  namespace: forgejo
type: Opaque
stringData:
  privateKey: ENC[AES256_GCM,data:CIvOWYBzSgIEcSikyZbLOtc5AM7oORfHetZV0imC94W31gBZP/6o3mLqG8sYZUsn6wAqAgEpYFkzL/pIj3jbq0E19f3tSQm7Zx/bIP9P5v93n0NyImYELQRld8+yrYlfgyYJtAmgYHFoXUoFw5N6GnScnqTVTg3P9s3HgNaIehpT7x34hulZdiW5IcdbT2lIbZKmH3pwjhRsQaZ2IQoUyM70bA2zOYc7XPVQWJAqJvGtOb1yVucgb4DNeiLbJw/2C36hPeV6mxjbwf/0iFKQX0qOVzBhB0erkgZlW4ey7np3A325KCy51lpD5j5/pu+/fkIdS4voXSADW4uT8T0TINJKfMSBr97t6/A92kBBmsMyR74aXR0/oVMOFUdvr97IY9xBhvTRAhd/KUs0FfNZ8a3cYhtJBpOrjpsN9OaU8yhxEiLfx5ZBVQ5pTTXo7M6evHeY4e1Px7GcNfMtIycx3WBSdAeR1K5w5oXxSyuDZCKOf2FbkIcQH8GfN8Tsla7m+efJwK37+tobPrp8VmnQsK7n+Lu1POeL6xmV1YXjZ1Lt/pGLGfqKOIsIvqFZjHv8,iv:oDfv4jTuGSip41C+Op3G10rN+gADcK7QgbMMv5VY0Rs=,tag:slzCXUn7jXxjX7BsoQJI8w==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dDdCdEtxcnRIMkJGSUN0
        M21JejJmek1LR05FZE1VYktTNkxqb0pFRVQ4CkZ6M05oNjBKZ0xzMEptUThzbHNF
        UEdEdGJMY1lwY3A4U0YrWEROU1ZpSkUKLS0tIGo2T3E4VnU3MTJaaERyWGU2L0FH
        MjdIQXZXWXVoRXpEOWpNT3MyYXpYUFUKr+tpbXwjz72FUbh59A/s8Cr/EbXh8OvM
        D3AJkqRHnh6apIDDpN2+AkQvpiZ9AVHuzxNR2PxZUDIMf1V5eo5JXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T04:17:13Z"
  mac: ENC[AES256_GCM,data:xH+h3s5jeHEE1aH7StklmuHkxZOi+5ZLK8uOF0bDmEyEvh5FEltkp28gK4ahEHii0vlBY7bgSreopOj1PTE79qLVPSGRpl3qeq+EgSLrfEZMlkk4Js8t0om5P2ooI4qtg3lS5YW6oUxslpQq25Q9CzQ+krqSaH3aE6dCkbPaOlM=,iv:bY/ibfsofxXTCs8707UbQMIbeZ0+ga11AGnBzhwh12A=,tag:1oGtPEIAKus7sSGLb9yFFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
