apiVersion: v1
kind: Secret
metadata:
  name: secrets-forgejo-s3
  namespace: forgejo
type: Opaque
stringData:
  access-key: ENC[AES256_GCM,data:+Hj8PXAAvFlg5EmMbMtGANKPKwywBKEFM4E=,iv:P9DVYhlpfLw2yRUm66Bs/Hi5+zHZmYxr70Qu0tjqHto=,tag:6NOVvHzj6Amh+Scaj0oEAw==,type:str]
  secret-key: ENC[AES256_GCM,data:bfAd7Zzx5G19LV0ruS3BpD9LQPCiMTRVXm7Veapo6ubZ6Q369UPvYMjFFVyJ552u9GnWyb/Cho6IfjTP61vx+Q==,iv:08fNNsCdavwpmV+t3ZdL8AS25s/68pJKXI0dYtXXeXQ=,tag:fDLqH3nbdIF4EXpMdEW8DQ==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcFJzN1lUQ3IrdStLSE9O
        bjVPaUUrK3hRZVE1Y002UGphWnIvMTZsTDFvClRWS3ZCOVo5UHMxS044Vzdwd1E4
        QUpyM1hyN09GY2N3UnQ2REVtaFRxN00KLS0tIHRqNVlDL00zbjNHUU04Zm5VN05s
        RTZOY0QwbmFBWUVpM0FHejhpN3F4NkUK8gKCD9et2zLrGt83qsvbiV5lfqTKaoWM
        EJbFA6Wr/zUD5wqRoeFmC7Hi1iNNoeA7p6IUeLpxhuR3J4ixQOWetg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T03:23:15Z"
  mac: ENC[AES256_GCM,data:ts527o7Nw0ODwiTTUABrau68S+AS8vQ/BtEHv1o0GwHRAlw7wzDM1RlKEqYxUFg7uw8npjmM+5tHgybxDfbMDn7sKrQG/I+iZU2UBGdxy3wNEkfdGc8KDxJpFMpM1HS08cD/qlxDc438V4OBARHPdTFNbJn/Gi8UZh62LI1N3QU=,iv:X3e4dIHSGH3HscvgNf/AIgp2PKnsl1kWhoM7ySOfJqg=,tag:AiDUuUm4WdjnZs2MDfHW5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
