apiVersion: v1
kind: Secret
metadata:
  name: secrets-forgejo-oidc
  namespace: forgejo
type: Opaque
stringData:
  key: ENC[AES256_GCM,data:etGgB45IqbjeKNtgKBYD56Be4e5WoGLuqFXlgcGjAnEoBuif,iv:o/TPWKPKFFPKYEyeNNcKUGVVj9Swmd/RNjKO89j+0tY=,tag:W5ArJGCSkMSmr5AwpoXCaw==,type:str]
  secret: ENC[AES256_GCM,data:6ZTCb+fd2rRlaVImZmRAjhhPtHjn2ZwGg7SWlxYxjaw=,iv:Q91Nm0Lx3sQdVZBVLTZ+CX8Jo9o7gKUyY9iuqYliQT8=,tag:nNwLdAShxVylz93xwUxVDg==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlREwxbElqZHUzb3BJeklr
        bmVZbHpPZUVXOGIwQksyaWc4OVFYWWZRc0drClh1dnR6QmJFOGl2YUtXcXVBbWFv
        U01jcDJIdFpKRXVYbnZ0c2NVOGV3b0UKLS0tIEYwc1JWejZoblVtN0Z3MUpWelVM
        QlhYQ2FBUVN0V2tOZWxybXZIZFZzeEUKgjdVEJBad71DgeQQhdYQRUNcS/TXx2Aq
        bO3i8kUeEZoTQp5LtGtjAjK00s2AuOHhHl495c/w+ktp48AMDIahVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-29T05:29:50Z"
  mac: ENC[AES256_GCM,data:0Nry55DfE7T+q6sKk1jG6+wEBdBk2rnVlmj6a10OlegDNsimsM56JIz2PFtx0nbJ92G9YMF1yWlOd/n7ZpMgQGAJr+brZioeaN5WM7vENqzlLH8zPyibA+lkwqDPIY2fcOE0OHi/haPLUWqiXfNnpi2rUUtGkmHm8iY6HPv67ow=,iv:egRyGNubUo0rZdSfb/TABkhlUr4B80ZjGnLzIjSnp7o=,tag:+r9eOthgGuLNbKNyqoJwZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
