apiVersion: v1
kind: Secret
metadata:
  name: idp
  namespace: pomerium
type: Opaque
stringData:
  client_id: ENC[AES256_GCM,data:b/PGnKy85bne8cAhomtywX4X/jctR0mbNLKWL6IpBVJj2qGPdRQXpg==,iv:e3RWYaUzVUYPNkrYDCNpudEO+tK3SA3SegSQuWt0rHg=,tag:N1VTYuuigIORBxOT8V/CYg==,type:str]
  client_secret: ENC[AES256_GCM,data:AoLpZHE7dmIu6dL6/t8D5XgDs6eLk7s51o6WC0EmJRpOifzP5QsDcBUfMUvsA9ZzvM9XhugrU0yMKoCsiGLjC42kmh2cEb6h+9nn6L/Wxs7yELb5TW+Ol4MPKDFYMSLQrexwV++LwVwHbGj7wN7wAh97oUn1zdmQltcUYP4PhzU=,iv:AvJgSoQE472YgVw/mHAMyqvOp15sHAkO3Md085ruW7Y=,tag:71Bapymw6B0LLJNVZl33yQ==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ2llditjemtieVN5TWtO
        a3k0akhhL3BUK2FMYzU2MjVDNVN3blV3YkdzCnFlN0FqVDdoR2V5aDNhUzZXcEg0
        K1o2bHpYNjBTOUExbnhqOFE1d0w1RTAKLS0tIFNWMTFBeFZZUmlSOGsxVjhFQWlz
        MmM1MjI3VEpMVDJNaVBISFNsMmJQdkUKo91VOhdUrPVm9H2dcfxn9tYw0sXI+lim
        d13JeT1B1ZbSzQVlpKfp7NHWoBQiiFmFHveE8gZTJqNNRULT+I3flQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T18:39:04Z"
  mac: ENC[AES256_GCM,data:x40ucOUOdSyDgTWfRix5tHEkSf7GqwaSCcer0cNaQ0BVoc0pKxLdIw8oQhH0cL6oy1/7D3iTgMC6TB3F1vvwrz0c+Yu56rY/uURBUL97zgiXIkavQ/ou6skgVhiG/UCzbOwgl5ncy+RwXRnDp5ninv4D1lrAdJ3ECjr7DE3Ea0s=,iv:LBHqwxOZpVaIjDBK3onmlHGR/8rMW/3XafvcWuXNg+U=,tag:YsqlsYPoTN3y3pLpBBjqcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
