---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kirocrew-data
  namespace: kirocrew
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
  storageClassName: sunbeam-nfs-csi
