apiVersion: v1
kind: Secret
metadata:
  name: secrets-kirocrew
  namespace: kirocrew
type: Opaque
stringData:
  OPENCODE_AUTH_CONTENT: ENC[AES256_GCM,data:RrCdJleoWF5GQlkSw3uq0DQeBdk6zziELoNbxCCzj+VLDQwFTFZ2pC2DAuvMC0Q4uwgRMC5m3G7EBO0c+ehDavWJ0UHE/iOVqnJKSPGrzd7UVhg80rWKyUJ32qHjSaI7Lg==,iv:u1Ev+oJBd4tapvimiMPFXVKaIWl5/pxRZM3t+o5C//o=,tag:wr7v60DuwOBM0qb9OktHvw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWkJQSnMyS205dkJadzV4
        WitXY1VlOG5HNWFqaFErLzEvVTVPcm1EblJnCmZ2WFI1bDN5ajBTS3RCSFo4anJK
        aEIzcHhJMXJRdHphWUJlc0VseEFnY0UKLS0tIG94b2ZWbVBDTmVWTG93UndOM0xj
        RkNFUVduSWNoVlp0YVpxdk5sYlk3TnMK/TvRwxNilNjQh7bn2PLOXjHNll0M6qyw
        rU2V9WR2YPa45sZrZSroqUi6Kw2F5z3KDrZQztE0tvOnEHf57S8tKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T04:39:27Z"
  mac: ENC[AES256_GCM,data:SgYfVMb4YCE191HxH0CiKoCpdmLLH+9SuSUg8UUvZ81Jq9w+XSC6R25IRPMUhoH1bL3pVzozcwhrgSl2kEPqWZMklvgWkQ6BfXYL1vdAwEJz4yibuAjENs8C7cVZcAwqLQeVTbXjfh+xiYN1zntelZ7WcuwnoQg7fMzmQ+sS9xM=,iv:Ra0PQIQRkq2ez9IWIpF4PKQ6YMnEN21DKr8lwx/p52c=,tag:A8Beu+f5GGagweeF3mfDFA==,type:str]
  version: 3.13.3
