apiVersion: v1
kind: Secret
metadata:
  name: truenas-secret
  namespace: hpe-storage
type: Opaque
stringData:
  serviceName: ENC[AES256_GCM,data:g4mU7BUTECViRnxUF5H8,iv:Z7MhyHWdZX0McqNCcMsmzMgyj53GS0s3N3daKq4+uTI=,tag:XMK7Sbezi/7RQL7GrERYFA==,type:str]
  servicePort: ENC[AES256_GCM,data:PWBgsg==,iv:qOg0LXO7uWWZ3qw5llVQIdTXEsVL/ba9rVS1Q5YTy40=,tag:BYFJmSG6YPupnjFpRJwuqw==,type:str]
  username: ENC[AES256_GCM,data:jQOhRASc0A==,iv:DndKGjsRIaDEqTwoq4TKEXqbTBSca2hfSneQoNR1IiA=,tag:jMYbTdwhh4OlJs3GYLhWmQ==,type:str]
  password: ENC[AES256_GCM,data:N16aK+gpEab/KWC00BKv8rojMJoswpdDdOi432U3nA9Vd0Dw2H6okCYtCaJ8hZ6XV9uK4K51QlN0/CbHPgQWAfSI,iv:+df1f135prUYa7oArtVi3rbNJBkE7mJrN9RRIz8BvXY=,tag:a4NSihsRDp95Pmokkr6LNg==,type:str]
  backend: ENC[AES256_GCM,data:OdEW9uMnUPH8Dg==,iv:xQFp5gJiPaEPCrODp+AU7y5503eKnJ6wREPdL9yiHCY=,tag:4ap35St0fQLpkEcN95Ok9w==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRnlXTUxUVkNKRzZ3ZEpT
        cFErWVk4NFNuelhoUE1pMzhQTkZqaWZUaTNzCkhDWFk2TTFwVmFObitBWlNpbnJz
        a1JBSjBaUmRyUE5sRDU0ZWVEQmw5TVEKLS0tIGp4UVdnczZOM08zMTQxYWd6SDZx
        c0pPN1VmQWlXNDU1akNhZWhBZk4zclEKXATSYfTHsN0IbB3OaYZLe7gcqaHVs6TX
        UhJq9QNIPUCv07BFEPGuhOFyL7u1sY1RH2nIjI1LK4IDtNzjuX65HA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-18T20:04:44Z"
  mac: ENC[AES256_GCM,data:zFi5BDJNgRgVkxUTtvMOZ6p6MgGYE//Am4KbqdB3kouqcibm/4Rwabrlz0zvYjzEX7HvOTBXkXsCNbU3ZfmRZ3zMprCcIkXj+0IZuWAT1JynxtvcObzLYqMxG33d9fiJ08/vMLIgVY0vby2fBW4Bh/xHKag08EhJ5evckQ6U1CM=,iv:zVlKIjbhiC9psRffV5kwq226bW+XBnLmoy0etDV0r8U=,tag:AK2a+U9Y+/GvNtJhkBCIrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
