---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-immich
  namespace: immich
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  imageName: ghcr.io/layertwo/cloudnative-pgvecto-rs:16.6
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      postInitSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube";
        - CREATE EXTENSION IF NOT EXISTS "earthdistance";
  storage:
    storageClass: sunbeam-nfs-csi
    size: 4Gi
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://layertwo-dev-cloudnativepg/
      endpointURL: https://62eaebf5ed37822b342914fbdc45a08d.r2.cloudflarestorage.com
      serverName: immich
      s3Credentials: 
        accessKeyId:
          name: &secretName secrets-cloudnativepg-r2
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: *secretName
          key: SECRET_ACCESS_KEY
