---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: mediabox
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      main:
        containers:
          radarr:
            image:
              repository: ghcr.io/onedr0p/radarr
              tag: 5.8.3.8933
            env:
              TZ: Etc/UTC
              RADARR__APP__INSTANCENAME: Radarr
              RADARR__APP__THEME: dark
              RADARR__AUTH__METHOD: External
              RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
              RADARR__LOG__DBENABLED: "False"
              RADARR__LOG__LEVEL: info
              RADARR__SERVER__PORT: &port 7878
              RADARR__POSTGRES__HOST:
                secretKeyRef:
                  name: cnpg-radarr-app
                  key: host
              RADARR__POSTGRES__USER:
                secretKeyRef:
                  name: cnpg-radarr-app
                  key: user
              RADARR__POSTGRES__PASSWORD:
                secretKeyRef:
                  name: cnpg-radarr-app
                  key: password
              RADARR__POSTGRES__MAINDB: radarr_main
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsGroup: 568
              runAsNonRoot: true
              runAsUser: 568
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
                ephemeral-storage: 1Gi
              limits:
                cpu: 1000m
                memory: 8192Mi
                ephemeral-storage: 2Gi
    defaultPodOptions:
      dnsConfig:
        nameservers:
          - 1.1.1.1
        options:
          - { name: ndots, value: "1" }
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: *port
            protocol: HTTP
    persistence:
      config:
        enabled: true
        storageClass: sunbeam-nfs-csi
        accessMode: "ReadWriteOnce"
        size: 16Gi
        advancedMounts:
          main:
            radarr:
              - path: /config
      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: &limit 8Gi
        advancedMounts:
          main:
            radarr:
              - path: /tmp
      varlogs:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: *limit
        advancedMounts:
          main:
            radarr:
              - path: /var/logs
      varrun:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: *limit
        advancedMounts:
          main:
            radarr:
              - path: /var/run
      media:
        type: nfs
        server: sunbeam.layertwo.lan
        path: /mnt/storage0/media
        advancedMounts:
          main:
            radarr:
            - path: /movies
              subPath: movies
            - path: /downloads
              subPath: downloads

