apiVersion: v1
kind: Secret
metadata:
  name: secrets-forgejo-valkey
  namespace: forgejo
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:RUbzFKxbSQKBKuhcThl1V0XHM065p25wL3E9FT1dFIzHlfsBVxn+tNWsOKt4s8ljdIh+1xkrnZToFMroKU2Ymw==,iv:I3OtIkfF9dHeuYT/qHo5Tf5HS1fT67VyEjXry+t/Fpo=,tag:2DxqAw2IwCEQ4l7SIwljUA==,type:str]
  replication-password: ENC[AES256_GCM,data:ZH5pOfu/YIbFdPNTW0KcTOFX0ynITn/Bzu9Y6ilp+NsVXHYkYULha6nCqi+YEePQZp50TY1bGz0DzGlByPJIBA==,iv:vqHkWUf6MrZax4IS0svAeqKT+u+FfAj+YOj770NlEsA=,tag:gJU6QvkMJK3T9Q2vqQ8ubQ==,type:str]
sops:
  age:
    - recipient: age140p5gj8xeqccpu283eycwhq7kwjrwug9emmj5mucn4j80jjzfd6qsnuv3y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNW5MNUdOT2NpcXZ3eFVC
        bnRPTTNqYVlKVUVZcVQybGlZME9keGdiY0ZBCmJvZU94aUNzeUVxamdFU3VDMTZQ
        cG9Ba2cvOTRUbEhOS0I1OHl3ZGFtS1EKLS0tIEdiR01JMjdndHdnRDgrMHNPaGJV
        NTBONVh4dmJ0MENrTnQ0QWE5bDZrRHcKc+irtmNGjeC4g9gWjVyVHLPUZKD0bYqd
        4GABZeln7NbIWWqSq7QRPrz6fxOXrwKEgpNMs1eZFJ2mL7lKnZi4mw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T01:36:49Z"
  mac: ENC[AES256_GCM,data:YyAHCOz0K19VNKYG1l0TqeD1Ui8iYKecR0DgJzXbE1C2wRJeEM+2anWYkCSu7o2F5KyFi18be8oEmnMgmfatZNaYLcfO3/0fgZG0CQgIY1oHA1c+avcUOVuH61aHzD4d4bhWEf5mg16VhgHIKXBUoKuansAf+WaGwngdo+jCsEM=,iv:tFRFyUkmeLXNPzNboowPKnabjdB51VDZI4ulQcYsDFA=,tag:n8lOQPRR3r26KtiNK0ccgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
