name: cloudflare-ddns

on:
  workflow_dispatch:
  push:
    paths:
      - containers/cloudflare-ddns/**
      - .github/workflows/cloudflare-ddns-docker-image.yml
  pull_request:
    branches: [ "mainline" ]
    paths:
      - containers/cloudflare-ddns/**
      - .github/workflows/cloudflare-ddns-docker-image.yml

env:
  REGISTRY: ghcr.io

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./containers/cloudflare-ddns

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run linting
        run: |
          black --check src tests
          isort --check-only src tests
          flake8 src tests

      - name: Run tests
        run: pytest --junitxml=reports/results.xml

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: containers/cloudflare-ddns/reports/results.xml

  package:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success() && (github.event_name == 'pull_request' || github.ref == 'refs/heads/main')

    permissions:
          contents: read
          packages: write
          id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Install cosign
      if: github.event_name != 'pull_request'
      uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0
      with:
        cosign-release: 'v2.1.1'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
      with:
        context: containers/cloudflare-ddns
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/layertwo/cloudflare-ddns:latest
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Sign the published Docker image
      if: ${{ github.event_name != 'pull_request' }}
      env:
        TAGS: ${{ steps.meta.outputs.tags }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
      run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
