name: flux-local

on:
  workflow_dispatch:
  pull_request:
    branches: [ "mainline" ]
    paths:
      - clusters/home/**
      - .github/workflows/flux-local.yml

jobs:

  diff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@v2.8.2
      - uses: allenporter/flux-local/action/diff@8.1.0
        id: diff
        with:
          live-branch: mainline
          path: clusters/home
          resource: helmrelease
          skip-invalid-kustomization-paths: true

      - name: PR Comments
        uses: mshick/add-pr-comment@v3.1.0
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-id: ${{ github.event.pull_request.number }}/clusters/home/${{ matrix.resource }}
          message-failure: Unable to post kustomization diff
          message: |
            `````diff
            ${{ steps.diff.outputs.diff }}
