name: flux-diff

on:
  workflow_dispatch:
  pull_request:
    branches: [ "mainline" ]
    paths:
      - clusters/home/**
      - .github/workflows/flux-diff.yml

jobs:

  diff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: "0"
      - uses: fluxcd/flux2/action@v2.9.5
      - uses: home-operations/flate/action@v0.6.2
        with:
          cache: true
      - id: diff
        env:
          FLATE_OUTPUT: github
          FLATE_BASE: mainline
          FLATE_PATH: ./clusters/home
        run: |
          diff=$(flate diff all)
          {
            echo 'diff<<EOF'
            echo "${diff}"
            echo 'EOF'
          } >> "${GITHUB_OUTPUT}"

      - name: PR Comments
        uses: mshick/add-pr-comment@v3.12
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-id: ${{ github.event.pull_request.number }}/clusters/home/${{ matrix.resource }}
          message-failure: Unable to post kustomization diff
          message: |
            `````diff
            ${{ steps.diff.outputs.diff }}
