name: flux-local

on:
  workflow_dispatch:
  pull_request:
    branches: [ "mainline" ]
    paths:
      - clusters/home/**
      - .github/workflows/flux-local.yml

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@v2.4.0
      - uses: allenporter/flux-local/action/test@7.0.0
        with:
          path: ./clusters/home
          enable-helm: true

  diff:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    strategy:
      matrix:
        resource:
          - helmrelease
          - kustomization

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@v2.4.0
      - uses: allenporter/flux-local/action/diff@7.0.0
        id: diff
        with:
          live-branch: mainline
          path: clusters/home
          resource: ${{ matrix.resource }}
      - name: PR Comments
        uses: mshick/add-pr-comment@v2
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-id: ${{ github.event.pull_request.number }}/clusters/home/${{ matrix.resource }}
          message-failure: Unable to post kustomization diff
          message: |
            `````diff
            ${{ steps.diff.outputs.diff }}
            `
