name: flux-diff

on:
  workflow_dispatch:
  pull_request:
    branches: [ "mainline" ]
    paths:
      - clusters/home/**
      - .github/workflows/flux-diff.yml

jobs:

  diff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: "0"
      - uses: fluxcd/flux2/action@b9c17924adb533d3617ec7de97a7b0f4acc07b39 # v2.9.6
      - uses: home-operations/flate/action@631b76b69c4e58c6f4d1cb01e23616fa61aebafa # v0.6.5
        with:
          cache: true
      - id: diff
        env:
          FLATE_OUTPUT: github
          FLATE_BASE: mainline
          FLATE_PATH: ./clusters/home
        run: |
          diff=$(flate diff all)
          {
            echo 'diff<<EOF'
            echo "${diff}"
            echo 'EOF'
          } >> "${GITHUB_OUTPUT}"

      - name: PR Comments
        uses: mshick/add-pr-comment@ec328af66588ab8f77cdeb2c264f14aba45bbf59 # v3.12
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-id: ${{ github.event.pull_request.number }}/clusters/home/${{ matrix.resource }}
          message-failure: Unable to post kustomization diff
          message: |
            `````diff
            ${{ steps.diff.outputs.diff }}
