---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cloudtak
  namespace: tak
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  imageName: ghcr.io/cloudnative-pg/postgis:17.9-3.6.2-standard-trixie
  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS postgis CASCADE;
  storage:
    storageClass: sunbeam-iscsi-csi
    size: 4Gi
  walStorage:
    storageClass: sunbeam-iscsi-csi
    size: 10Gi
